project_id = "kqygnqetygcvkaauwbji"

[functions.create-builder-checkout]
verify_jwt = false

[functions.create-signature-checkout]
verify_jwt = false

[functions.analyze-builder-references]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.bokun-list-products]
verify_jwt = false

[functions.test-webhook-simulate]
verify_jwt = false

