import { appendFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import type {
  FullConfig,
  FullResult,
  Reporter,
  TestCase,
  TestResult,
} from "@playwright/test/reporter";

import {
  CTA_PARITY_ATTACHMENT_NAME,
  type CtaParityReport,
  type ParityCheck,
} from "../cta-parity-helpers";

/**
 * CI-facing summary reporter for the hero CTA parity suite.
 *
 * Reads the structured `cta-parity-report` JSON attachments produced
 * by `runParityChecks` and renders a per-viewport pass/fail + deltas
 * table to:
 *   • $GITHUB_STEP_SUMMARY (when running on GitHub Actions)
 *   • stdout (always, so the same report is visible in local runs)
 *   • playwright-report/cta-parity-summary.md (for artifact download)
 *
 * Each row shows the field, primary value, secondary value, measured
 * delta, allowed tolerance, and ✅/❌ status — so a regression makes
 * the drifted field immediately obvious without digging into traces.
 */

type Collected = {
  viewportLabel: string;
  viewportWidth: number;
  viewportHeight: number;
  testTitle: string;
  status: TestResult["status"];
  report: CtaParityReport;
};

const ARTIFACT_PATH = "playwright-report/cta-parity-summary.md";

export default class CtaParitySummaryReporter implements Reporter {
  private collected: Collected[] = [];

  onBegin(_config: FullConfig) {
    this.collected = [];
  }

  onTestEnd(test: TestCase, result: TestResult) {
    for (const att of result.attachments) {
      if (att.name !== CTA_PARITY_ATTACHMENT_NAME) continue;
      if (!att.body) continue;
      try {
        const report = JSON.parse(att.body.toString("utf8")) as CtaParityReport;
        this.collected.push({
          viewportLabel: report.viewportLabel,
          viewportWidth: report.viewportWidth,
          viewportHeight: report.viewportHeight,
          testTitle: test.title,
          status: result.status,
          report,
        });
      } catch {
        // Ignore malformed attachments — the test itself will have failed.
      }
    }
  }

  onEnd(_result: FullResult) {
    if (this.collected.length === 0) {
      // Nothing to summarize — parity tests didn't run in this shard.
      return;
    }

    // Sort by viewport width so the table reads mobile → tablet → desktop.
    this.collected.sort(
      (a, b) => a.viewportWidth - b.viewportWidth || a.viewportHeight - b.viewportHeight,
    );

    const md = this.renderMarkdown();

    // Write to GitHub Actions step summary if available.
    const stepSummary = process.env.GITHUB_STEP_SUMMARY;
    if (stepSummary) {
      try {
        appendFileSync(stepSummary, md + "\n");
      } catch (err) {
        // Non-fatal — fall through to stdout + artifact.
        console.warn(`[cta-parity-summary] could not write step summary: ${String(err)}`);
      }
    }

    // Always mirror to stdout so local runs see it too.
    process.stdout.write("\n" + md + "\n");

    // Persist as a downloadable artifact alongside the HTML report.
    try {
      mkdirSync(dirname(ARTIFACT_PATH), { recursive: true });
      writeFileSync(ARTIFACT_PATH, md, "utf8");
    } catch (err) {
      console.warn(`[cta-parity-summary] could not write artifact: ${String(err)}`);
    }
  }

  private renderMarkdown(): string {
    const lines: string[] = [];
    const totalFailed = this.collected.reduce((n, c) => n + c.report.failedCount, 0);
    const overall =
      totalFailed === 0
        ? "✅ all viewports passed"
        : `❌ ${totalFailed} drift${totalFailed === 1 ? "" : "s"} detected`;

    lines.push("## Hero CTA parity — per-viewport summary");
    lines.push("");
    lines.push(`**Status:** ${overall}`);
    lines.push("");
    lines.push(
      "Each row compares the **primary** CTA (Design your day) vs the **secondary** CTA (Explore Signature Experiences). The two buttons must mirror each other in geometry, typography, and icon layout — only fill/border/color may differ.",
    );
    lines.push("");

    for (const c of this.collected) {
      const headline =
        c.report.failedCount === 0
          ? "✅ pass"
          : `❌ ${c.report.failedCount}/${c.report.totalCount} failing`;
      lines.push(`### ${c.viewportLabel} — ${c.viewportWidth}×${c.viewportHeight} — ${headline}`);
      lines.push("");
      lines.push("| Field | Primary | Secondary | Δ | Tolerance | Status |");
      lines.push("| --- | ---: | ---: | ---: | ---: | :---: |");
      for (const check of c.report.checks) {
        lines.push(renderRow(check));
      }
      lines.push("");
    }

    lines.push(
      "_Generated by `e2e/reporters/cta-parity-summary.ts`. Raw per-test JSON is attached to each Playwright test result as `cta-parity-report`._",
    );
    return lines.join("\n");
  }
}

function renderRow(check: ParityCheck): string {
  const status = check.passed ? "✅" : "❌";
  if (check.kind === "numeric") {
    return `| ${check.label} | ${fmtPx(check.primary)} | ${fmtPx(check.secondary)} | ${fmtPx(check.delta)} | ≤ ${fmtPx(check.tolerance)} | ${status} |`;
  }
  if (check.kind === "single") {
    const primaryCell = check.target === "primary" ? fmtPx(check.value) : "—";
    const secondaryCell = check.target === "secondary" ? fmtPx(check.value) : "—";
    return `| ${check.label} | ${primaryCell} | ${secondaryCell} | ${fmtPx(check.value)} | ≤ ${fmtPx(check.tolerance)} | ${status} |`;
  }
  return `| ${check.label} | \`${escapeCell(check.primary)}\` | \`${escapeCell(check.secondary)}\` | — | exact match | ${status} |`;
}

function fmtPx(n: number): string {
  return `${n.toFixed(2)}px`;
}

function escapeCell(v: string): string {
  return v.replace(/\|/g, "\\|");
}
