import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import lastRun from "@/generated/e2e-last-run.json";

export const Route = createFileRoute("/admin/e2e-report")({
  head: () => ({
    meta: [
      { title: "E2E results — Studio Admin" },
      {
        name: "description",
        content: "Pass/fail, duration and failing assertions from the last Playwright E2E run.",
      },
      { property: "og:title", content: "E2E results — Studio Admin" },
      {
        property: "og:description",
        content: "Pass/fail, duration and failing assertions from the last Playwright E2E run.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
      { name: "robots", content: "noindex, nofollow" },
    ],
  }),
  component: E2eReportPage,
});

interface TestRow {
  file: string;
  title: string;
  status: string;
  durationMs: number;
  retries: number;
  errors: string[];
}

interface RunSummary {
  generatedAt: string | null;
  startedAt: string | null;
  durationMs: number;
  total: number;
  passed: number;
  failed: number;
  flaky: number;
  skipped: number;
  tests: TestRow[];
}

const run = lastRun as unknown as RunSummary;

function secs(ms: number): string {
  if (ms < 1000) return `${Math.round(ms)} ms`;
  if (ms < 60_000) return `${(ms / 1000).toFixed(1)} s`;
  return `${Math.floor(ms / 60_000)}m ${Math.round((ms % 60_000) / 1000)}s`;
}

function statusTone(status: string): string {
  if (status === "expected" || status === "passed")
    return "border-[color:var(--teal)]/30 text-[color:var(--teal)]";
  if (status === "flaky") return "border-[color:var(--gold)]/50 text-[color:var(--gold-ink)]";
  if (status === "skipped") return "border-[color:var(--charcoal)]/20 text-[color:var(--charcoal-soft)]";
  return "border-red-500/40 text-red-700";
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-[color:var(--charcoal)]/10 bg-[color:var(--sand)]/40 p-4">
      <div className="text-[10.5px] uppercase tracking-[0.22em] text-[color:var(--charcoal-soft)]">
        {label}
      </div>
      <div className="mt-1 font-[family-name:var(--font-editorial)] text-2xl text-[color:var(--charcoal)]">
        {value}
      </div>
    </div>
  );
}

function E2eReportPage() {
  const [onlyFailing, setOnlyFailing] = useState(false);

  const grouped = useMemo(() => {
    const rows = onlyFailing
      ? run.tests.filter((t) => t.status !== "expected" && t.status !== "passed")
      : run.tests;
    const map = new Map<string, TestRow[]>();
    for (const t of rows) map.set(t.file, [...(map.get(t.file) ?? []), t]);
    return [...map.entries()];
  }, [onlyFailing]);

  const empty = run.total === 0;

  return (
    <main className="mx-auto w-full max-w-3xl px-5 py-10">
      <p className="text-[11px] uppercase tracking-[0.22em] text-[color:var(--charcoal-soft)]">
        Studio admin
      </p>
      <h1 className="mt-2 font-[family-name:var(--font-editorial)] text-3xl leading-tight text-[color:var(--charcoal)]">
        Last E2E run
      </h1>
      <p className="mt-3 text-sm text-[color:var(--charcoal-soft)]">
        {run.generatedAt
          ? `Recorded ${new Date(run.generatedAt).toLocaleString()}.`
          : "No run recorded yet."}{" "}
        Generated by <code className="text-[12px]">bun run test:e2e:core-group</code>.
      </p>

      {empty ? (
        <div className="mt-8 rounded-lg border border-[color:var(--charcoal)]/10 p-6 text-sm text-[color:var(--charcoal-soft)]">
          Run the core group locally to populate this page:
          <pre className="mt-3 overflow-x-auto rounded bg-[color:var(--sand)]/50 p-3 text-[12px]">
            bun run test:e2e:core-group
          </pre>
        </div>
      ) : (
        <>
          <div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">
            <Stat label="Passed" value={String(run.passed)} />
            <Stat label="Failed" value={String(run.failed)} />
            <Stat label="Flaky / skipped" value={`${run.flaky} / ${run.skipped}`} />
            <Stat label="Duration" value={secs(run.durationMs)} />
          </div>

          <button
            type="button"
            onClick={() => setOnlyFailing((v) => !v)}
            className="mt-6 min-h-[44px] rounded-full border border-[color:var(--charcoal)]/15 px-5 text-[11px] uppercase tracking-[0.22em] text-[color:var(--charcoal)]"
          >
            {onlyFailing ? "Show all tests" : "Show only failures"}
          </button>

          <div className="mt-6 space-y-6">
            {grouped.map(([file, rows]) => (
              <section key={file}>
                <h2 className="font-[family-name:var(--font-editorial)] text-base text-[color:var(--charcoal)]">
                  {file}
                </h2>
                <ul className="mt-2 space-y-2">
                  {rows.map((t) => (
                    <li
                      key={`${file}-${t.title}`}
                      className="rounded-lg border border-[color:var(--charcoal)]/10 p-3"
                    >
                      <div className="flex flex-wrap items-center gap-2">
                        <span
                          className={`rounded-full border px-2 py-0.5 text-[10.5px] uppercase tracking-[0.18em] ${statusTone(t.status)}`}
                        >
                          {t.status}
                        </span>
                        <span className="text-[12px] text-[color:var(--charcoal-soft)]">
                          {secs(t.durationMs)}
                          {t.retries > 0 ? ` · ${t.retries} retry` : ""}
                        </span>
                      </div>
                      <p className="mt-2 text-sm text-[color:var(--charcoal)]">{t.title}</p>
                      {t.errors.length > 0 && (
                        <pre className="mt-2 max-h-56 overflow-auto whitespace-pre-wrap rounded bg-[color:var(--sand)]/50 p-3 text-[12px] text-[color:var(--charcoal)]">
                          {t.errors.join("\n\n")}
                        </pre>
                      )}
                    </li>
                  ))}
                </ul>
              </section>
            ))}
            {grouped.length === 0 && (
              <p className="text-sm text-[color:var(--charcoal-soft)]">
                No failing tests in the last run.
              </p>
            )}
          </div>
        </>
      )}

      <p className="mt-10 text-sm">
        <Link to="/admin" className="text-[color:var(--teal)] underline">
          Back to admin
        </Link>
      </p>
    </main>
  );
}
