import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { z } from "zod";
import { fallback, zodValidator } from "@tanstack/zod-adapter";
import auditReport from "@/generated/brand-audit.json";
import { BrandThemeSelect } from "@/components/BrandThemeSelect";
import { Logo } from "@/components/Logo";
import { BRAND_LOGO_THEMES, isBrandLogoTheme, type BrandLogoTheme } from "@/lib/brand-tokens";

/**
 * Sentinel value used when the URL carries a `?theme=` that is not a
 * valid `BrandLogoTheme`. We deliberately do NOT silently coerce to a
 * default here — the whole point is to surface the bad value to the
 * `<BrandThemeSelect>` runtime guard so the dev-only error panel
 * fires (and `console.error` is logged), exactly like any other
 * untrusted input source (CMS, DB, props).
 */
const INVALID_THEME_SENTINEL = "__invalid__" as const;

const themeSearchSchema = z.object({
  /**
   * `?theme=teal-on-ivory` etc. When the URL value is missing, we leave
   * it `undefined` (picker uses its own default). When the value is
   * present but invalid, we forward the raw string so the picker can
   * report it. `fallback()` (not `.catch()`) keeps the inferred type
   * intact — see TanStack search-params guidance.
   */
  theme: fallback(
    z.union([z.enum(BRAND_LOGO_THEMES as [string, ...string[]]), z.string()]),
    INVALID_THEME_SENTINEL,
  ).optional(),
});

export const Route = createFileRoute("/brand-qa")({
  component: BrandQAPage,
  validateSearch: zodValidator(themeSearchSchema),
  head: () => ({
    meta: [
      { title: "Brand QA — YES Experiences Portugal" },
      { name: "robots", content: "noindex, nofollow" },
      {
        name: "description",
        content:
          "Internal QA: live brand color audit comparing rendered tokens against the approved palette.",
      },
    ],
  }),
});

/**
 * APPROVED BRAND PALETTE — single source of truth.
 * Any drift between this list and the live CSS variables (or hex codes
 * referenced anywhere in the app) is reported as a failure below.
 *
 * NOTE: this file is the brand QA reference. The literal hex values below
 * are intentional — they are the canonical truth that the audit tool
 * (`scripts/site-brand-audit.mjs`) compares the rest of the codebase
 * against. Do not rewrite them to var() form.
 */
// brand-audit-ignore-file
const APPROVED = {
  teal: "#295B61",
  "teal-2": "#2A7C82",
  gold: "#C9A96A",
  "gold-soft": "#E1CFA6",
  ivory: "#FAF8F3",
  sand: "#F4EFE7",
  charcoal: "#2E2E2E",
  "charcoal-soft": "#6B6B6B",
} as const;

type TokenName = keyof typeof APPROVED;
const TOKEN_NAMES = Object.keys(APPROVED) as TokenName[];

// Hex codes that legitimately appear outside the brand palette.
// Pure black/white plus the dark-mode card surface are intentional.
const ALLOWLIST = new Set(
  [
    "#000",
    "#000000",
    "#fff",
    "#ffffff",
    "#1f1f1f", // dark-mode card surface
    "#ccc", // recharts internal selectors only
  ].map((h) => h.toLowerCase()),
);

/* ---------- color utilities ---------- */
function normalizeHex(input: string): string | null {
  const s = input.trim().toLowerCase();
  const m = s.match(/^#([0-9a-f]{3}|[0-9a-f]{6})$/);
  if (!m) {
    // try rgb(r,g,b)
    const rgb = s.match(/rgba?\(\s*(\d+)\D+(\d+)\D+(\d+)/);
    if (!rgb) return null;
    const [, r, g, b] = rgb;
    return "#" + [r, g, b].map((n) => Number(n).toString(16).padStart(2, "0")).join("");
  }
  let hex = m[1];
  if (hex.length === 3)
    hex = hex
      .split("")
      .map((c) => c + c)
      .join("");
  return "#" + hex;
}

function hexEq(a: string | null, b: string | null) {
  if (!a || !b) return false;
  return a.toLowerCase() === b.toLowerCase();
}

/* Build-time scan report — generated by scripts/brand-audit.mjs */
type AuditFinding = {
  file: string;
  line: number;
  col: number;
  raw: string;
  normalized: string;
  snippet: string;
  status: "approved" | "allowlisted" | "mismatch";
};
type AuditReport = {
  generatedAt: string;
  filesScanned: number;
  counts: { total: number; approved: number; allowlisted: number; mismatch: number };
  findings: AuditFinding[];
};
const audit = auditReport as AuditReport;

function BrandQAPage() {
  const [live, setLive] = useState<Record<TokenName, string | null>>(
    () => Object.fromEntries(TOKEN_NAMES.map((k) => [k, null])) as Record<TokenName, string | null>,
  );

  // Read the actually-rendered values of each --token from :root.
  useEffect(() => {
    const cs = getComputedStyle(document.documentElement);
    const next = {} as Record<TokenName, string | null>;
    for (const name of TOKEN_NAMES) {
      const raw = cs.getPropertyValue(`--${name}`).trim();
      next[name] = normalizeHex(raw);
    }
    setLive(next);
  }, []);

  const tokenRows = useMemo(
    () =>
      TOKEN_NAMES.map((name) => {
        const expected = APPROVED[name];
        const actual = live[name];
        return {
          name,
          expected,
          actual,
          ok: hexEq(actual, expected),
        };
      }),
    [live],
  );

  const findings = audit.findings;
  const mismatches = findings.filter((f) => f.status === "mismatch");

  const tokenPass = tokenRows.every((r) => r.ok);
  const refPass = mismatches.length === 0;
  const allPass = tokenPass && refPass;

  return (
    <main className="min-h-screen bg-background text-foreground">
      <div className="container-x py-16 md:py-20">
        <header className="mb-10 flex items-start justify-between gap-6">
          <div>
            <p className="eyebrow">Internal · Brand QA</p>
            <h1 className="mt-3 text-3xl md:text-4xl">Live palette audit</h1>
            <p className="mt-2 max-w-2xl text-sm text-[color:var(--charcoal-soft)]">
              Reads CSS custom properties from <code>:root</code> and compares them against the
              approved brand palette. Also verifies every hex code we knowingly reference resolves
              to an approved token (or an allowlisted neutral).
            </p>
          </div>
          <span
            className={
              "shrink-0 rounded-full border px-4 py-1.5 text-xs uppercase tracking-[0.2em] " +
              (allPass
                ? "border-[color:var(--teal)] text-[color:var(--teal)]"
                : "border-red-600 text-red-600")
            }
          >
            {allPass ? "All checks pass" : "Mismatch detected"}
          </span>
        </header>

        {/* Brand theme selector — runtime-guarded */}
        <BrandThemeSelectorPanel />

        {/* Palette swatches */}
        <section className="mb-12">
          <h2 className="mb-4 text-xl">Live tokens vs. approved hex</h2>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {tokenRows.map((row) => (
              <article
                key={row.name}
                className="overflow-hidden rounded-lg border border-[color:var(--border)] bg-card shadow-[var(--shadow-card)]"
              >
                <div
                  className="h-24 w-full"
                  style={{ background: `var(--${row.name})` }}
                  aria-label={`${row.name} swatch`}
                />
                <div className="space-y-1 p-4">
                  <div className="flex items-center justify-between">
                    <code className="text-xs">--{row.name}</code>
                    <span
                      className={
                        "rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider " +
                        (row.ok
                          ? "bg-[color:var(--sand)] text-[color:var(--teal)]"
                          : "bg-red-100 text-red-700")
                      }
                    >
                      {row.ok ? "OK" : "FAIL"}
                    </span>
                  </div>
                  <dl className="grid grid-cols-[auto_1fr] gap-x-3 text-xs text-[color:var(--charcoal-soft)]">
                    <dt>Expected</dt>
                    <dd className="font-mono">{row.expected}</dd>
                    <dt>Live</dt>
                    <dd className="font-mono">{row.actual ?? "—"}</dd>
                  </dl>
                </div>
              </article>
            ))}
          </div>
        </section>

        {/* Build-time scan results */}
        <section className="mb-12">
          <div className="mb-4 flex items-baseline justify-between">
            <h2 className="text-xl">Build-time scan</h2>
            <p className="text-xs text-[color:var(--charcoal-soft)]">
              {audit.filesScanned} files · {audit.counts.total} hex refs ·{" "}
              <span className="text-[color:var(--teal)]">{audit.counts.approved} approved</span>
              {" · "}
              {audit.counts.allowlisted} allowlisted
              {" · "}
              <span
                className={
                  audit.counts.mismatch ? "text-red-700" : "text-[color:var(--charcoal-soft)]"
                }
              >
                {audit.counts.mismatch} mismatch
              </span>
              {" · generated "}
              {new Date(audit.generatedAt).toLocaleString()}
            </p>
          </div>

          {mismatches.length > 0 && (
            <div className="mb-6 overflow-hidden rounded-lg border border-red-300 bg-red-50">
              <div className="border-b border-red-200 bg-red-100 px-4 py-2 text-xs font-semibold uppercase tracking-wider text-red-800">
                Mismatches ({mismatches.length})
              </div>
              <table className="w-full text-left text-sm">
                <thead className="text-xs uppercase tracking-wider text-red-700/70">
                  <tr>
                    <th className="px-4 py-2">File</th>
                    <th className="px-4 py-2">Hex</th>
                    <th className="px-4 py-2">Snippet</th>
                  </tr>
                </thead>
                <tbody>
                  {mismatches.map((f, i) => (
                    <tr key={i} className="border-t border-red-200">
                      <td className="px-4 py-2 font-mono text-xs text-red-800">
                        {f.file}:{f.line}
                      </td>
                      <td className="px-4 py-2">
                        <span className="inline-flex items-center gap-2">
                          <span
                            className="inline-block h-4 w-4 rounded border border-red-300"
                            style={{ background: f.normalized }}
                            aria-hidden
                          />
                          <code>{f.normalized}</code>
                        </span>
                      </td>
                      <td className="px-4 py-2 font-mono text-xs text-red-900/80">{f.snippet}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          <details className="overflow-hidden rounded-lg border border-[color:var(--border)] bg-card">
            <summary className="cursor-pointer bg-[color:var(--sand)] px-4 py-3 text-xs uppercase tracking-wider text-[color:var(--charcoal-soft)]">
              All findings ({findings.length})
            </summary>
            <table className="w-full text-left text-sm">
              <thead className="text-xs uppercase tracking-wider text-[color:var(--charcoal-soft)]">
                <tr>
                  <th className="px-4 py-2">File</th>
                  <th className="px-4 py-2">Hex</th>
                  <th className="px-4 py-2">Status</th>
                </tr>
              </thead>
              <tbody>
                {findings.map((f, i) => (
                  <tr key={i} className="border-t border-[color:var(--border)]">
                    <td className="px-4 py-2 font-mono text-xs">
                      {f.file}:{f.line}
                    </td>
                    <td className="px-4 py-2">
                      <span className="inline-flex items-center gap-2">
                        <span
                          className="inline-block h-4 w-4 rounded border border-[color:var(--border)]"
                          style={{ background: f.normalized }}
                          aria-hidden
                        />
                        <code>{f.normalized}</code>
                      </span>
                    </td>
                    <td className="px-4 py-2 text-xs">
                      {f.status === "approved" ? (
                        <span className="text-[color:var(--teal)]">Approved</span>
                      ) : f.status === "allowlisted" ? (
                        <span className="text-[color:var(--charcoal-soft)]">Allowlisted</span>
                      ) : (
                        <span className="text-red-700">Mismatch</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </details>

          <p className="mt-3 text-xs text-[color:var(--charcoal-soft)]">
            Generated by <code>scripts/brand-audit.mjs</code> on <code>predev</code> /{" "}
            <code>prebuild</code>. Run manually with <code>bun run brand:audit</code>.
          </p>
        </section>

        <div className="text-sm">
          <Link to="/" className="underline">
            ← Back to home
          </Link>
        </div>
      </div>
    </main>
  );
}

/* ------------------------------------------------------------------ */
/* Brand theme selector panel                                         */
/* ------------------------------------------------------------------ */
/* Theme is bound to `?theme=` in the URL via `validateSearch`. The   */
/* schema forwards unknown values through a sentinel so the picker's  */
/* runtime guard can show its dev-only error panel — no second copy   */
/* of the validation lives here.                                      */

/**
 * Pure presentational view of the theme selector. Exported so
 * integration tests can drive `?theme=` semantics without spinning up
 * a TanStack router. The route-bound wrapper below just feeds the
 * search-param value in and writes back via `useNavigate`.
 */
export interface BrandThemeSelectorViewProps {
  /** The raw `?theme=` value as it would arrive from the URL. */
  rawThemeParam: string | undefined;
  /** Called when the user picks a valid theme from the dropdown. */
  onSetTheme: (next: BrandLogoTheme) => void;
  /** Called by the dev buttons to forge an arbitrary URL value. */
  onSetRawTheme: (raw: string | undefined) => void;
}

export function BrandThemeSelectorView({
  rawThemeParam,
  onSetTheme,
  onSetRawTheme,
}: BrandThemeSelectorViewProps) {
  // Translate the validated search value into what BrandThemeSelect
  // expects: a valid BrandLogoTheme, or whatever raw thing the URL
  // carried so the dev error panel can name it.
  const themeForPicker: unknown =
    rawThemeParam === undefined
      ? "teal-on-ivory"
      : rawThemeParam === INVALID_THEME_SENTINEL
        ? // We lost the original string at the schema boundary; show the
          // sentinel so the dev panel still flags it as unsupported.
          INVALID_THEME_SENTINEL
        : rawThemeParam;

  return (
    <section className="mb-12" data-testid="brand-theme-panel">
      <h2 className="mb-4 text-xl">Brand theme selector (runtime-guarded)</h2>
      <p className="mb-4 max-w-2xl text-sm text-[color:var(--charcoal-soft)]">
        Bound to <code>?theme=</code>. The picker only emits values from <code>BrandLogoTheme</code>
        . Unsupported URL or prop values trip the same dev-only error panel and the underlying{" "}
        <code>&lt;Logo&gt;</code> guard (throws in dev, falls back in production).
      </p>

      <div className="grid gap-6 md:grid-cols-2">
        <div className="rounded-lg border border-[color:var(--border)] bg-card p-4">
          <BrandThemeSelect
            value={themeForPicker}
            onChange={onSetTheme}
            componentName="BrandQA.ThemeSelect"
          />
          <div className="mt-4 flex flex-wrap gap-2">
            <button
              type="button"
              onClick={() => onSetRawTheme("emerald-on-mauve")}
              className="rounded-md border border-destructive px-3 py-1.5 text-xs text-destructive"
            >
              Inject invalid ?theme
            </button>
            <button
              type="button"
              onClick={() => onSetRawTheme(undefined)}
              className="rounded-md border border-[color:var(--border)] px-3 py-1.5 text-xs"
            >
              Clear ?theme
            </button>
            <code
              className="ml-auto self-center text-xs text-[color:var(--charcoal-soft)]"
              data-testid="brand-theme-current-param"
            >
              ?theme={String(rawThemeParam ?? "")}
            </code>
          </div>
        </div>

        <div
          className="rounded-lg border border-[color:var(--border)] bg-[color:var(--ivory)] p-4 flex items-center justify-center min-h-[120px]"
          data-testid="brand-theme-preview"
        >
          {/* Only render the live Logo preview while the theme is valid;
              otherwise the Logo guard would throw in dev and unmount the
              whole panel before the dev-error message could be read. */}
          {isBrandLogoTheme(themeForPicker) ? (
            <Logo theme={themeForPicker} className="h-12 w-auto" />
          ) : (
            <span
              className="text-xs text-[color:var(--charcoal-soft)]"
              data-testid="brand-theme-preview-hidden"
            >
              Preview hidden while the selected theme is invalid.
            </span>
          )}
        </div>
      </div>
    </section>
  );
}

/** Route-bound wrapper: maps URL search params to `BrandThemeSelectorView`. */
function BrandThemeSelectorPanel() {
  const navigate = useNavigate({ from: "/brand-qa" });
  const search = Route.useSearch();

  const setTheme = (next: BrandLogoTheme) => {
    navigate({
      search: (prev: { theme?: string }) => ({ ...prev, theme: next }),
      replace: true,
    });
  };

  const setRawTheme = (raw: string | undefined) => {
    navigate({
      search: (prev: { theme?: string }) => ({ ...prev, theme: raw }),
      replace: true,
    });
  };

  return (
    <BrandThemeSelectorView
      rawThemeParam={search.theme}
      onSetTheme={setTheme}
      onSetRawTheme={setRawTheme}
    />
  );
}

/* Exported so tests can validate the same schema the router uses. */
// eslint-disable-next-line react-refresh/only-export-components
export { themeSearchSchema, INVALID_THEME_SENTINEL };
