/**
 * All-Signature map regression.
 *
 * Every valid Signature page is generated by the shared `/tours/$tourId`
 * route, so a single data regression can silently break the map section on
 * 12 pages at once. This suite enumerates every Signature ID and asserts
 * the shared resolver returns enough trustworthy, geo-resolved stops for a
 * useful map — in Source-of-Truth order, inside Portugal, without dupes.
 *
 * No coordinates or labels are invented here: the test only reads the SoT
 * itinerary and the verified `stopGeo` gazetteer.
 */
import { describe, expect, it } from "vitest";
import { signatureTours } from "@/data/signatureTours";
import { sotItinerary } from "@/data/signatureToursSourceOfTruth";
import { lookupStop } from "@/data/stopGeo";
import { resolveSignatureMapStops } from "@/lib/signature-map-stops";

/** Mainland Portugal bounding box — guards against transposed lat/lng. */
const PT_BOUNDS = { minLat: 36.8, maxLat: 42.2, minLng: -9.6, maxLng: -6.1 };

/** Below this a map is a pair of dots, not a route worth showing. */
const MIN_USEFUL_STOPS = 3;

describe("all Signature pages resolve a useful map", () => {
  it("covers exactly the published Signature collection", () => {
    expect(signatureTours.length).toBeGreaterThanOrEqual(12);
    expect(new Set(signatureTours.map((t) => t.id)).size).toBe(signatureTours.length);
  });

  it.each(signatureTours.map((t) => [t.id, t] as const))(
    "%s renders a map with enough trustworthy stops",
    (id, tour) => {
      const stops = resolveSignatureMapStops(tour);
      expect(stops.length, `${id} resolved only ${stops.length} map stops`).toBeGreaterThanOrEqual(
        MIN_USEFUL_STOPS,
      );

      for (const s of stops) {
        expect(s.label.trim().length, `${id} has an empty stop label`).toBeGreaterThan(0);
        expect(Number.isFinite(s.lat) && Number.isFinite(s.lng), `${id}: ${s.label}`).toBe(true);
        expect(s.lat, `${id}: ${s.label} latitude outside Portugal`).toBeGreaterThan(
          PT_BOUNDS.minLat,
        );
        expect(s.lat, `${id}: ${s.label} latitude outside Portugal`).toBeLessThan(PT_BOUNDS.maxLat);
        expect(s.lng, `${id}: ${s.label} longitude outside Portugal`).toBeGreaterThan(
          PT_BOUNDS.minLng,
        );
        expect(s.lng, `${id}: ${s.label} longitude outside Portugal`).toBeLessThan(
          PT_BOUNDS.maxLng,
        );
      }

      const keys = stops.map((s) => `${s.lat.toFixed(4)},${s.lng.toFixed(4)}`);
      expect(new Set(keys).size, `${id} has duplicate pin coordinates`).toBe(keys.length);
    },
  );

  it("has a coordinate for every visited SoT label (reports gaps, never invents)", () => {
    const gaps: string[] = [];
    for (const tour of signatureTours) {
      for (const chapter of sotItinerary(tour.id) ?? []) {
        if (chapter.stopType === "pass-by") continue;
        if (!lookupStop(chapter.label)) gaps.push(`${tour.id} → "${chapter.label}"`);
      }
    }
    expect(gaps, `Unmapped SoT labels:\n${gaps.join("\n")}`).toEqual([]);
  });
});
