/**
 * Slice D — Studio convergence + canonical route snapshot contract.
 *
 * Verification-only mirror. Proves:
 *   - after suitability filtering, no duplicate routeStop.id
 *   - commercialProductKey stays "studio-v3-private-full-day" through every
 *     handoff (identity guard)
 *   - Studio quote payload never carries a Signature-tour bokunProductId
 *   - a single canonical snapshot is captured at quote time and re-read by
 *     downstream surfaces — never regenerated by resolveStudioV3Route()
 */
import { describe, it, expect, vi } from "vitest";
import {
  STUDIO_COMMERCIAL_PRODUCT_KEY,
  assertStudioCommercialIdentity,
  isStudioCommercialProductKey,
} from "@/lib/pricing/studioCommercialIdentity";

type Composition = { adults: number; minorAges: number[] };
type RouteStop = { id: string; label: string; sequence: number };

// Canonical snapshot — the ONLY shape compared across surfaces.
type CanonicalRouteSnapshot = {
  commercialProductKey: string;
  travellerComposition: Composition;
  orderedStops: RouteStop[];
};

function normalizeSnapshot(
  key: string,
  comp: Composition,
  stops: Array<{ id: string; label: string }>,
): CanonicalRouteSnapshot {
  return {
    commercialProductKey: key,
    travellerComposition: {
      adults: comp.adults,
      minorAges: [...comp.minorAges].sort((a, b) => a - b),
    },
    orderedStops: stops.map((s, i) => ({ id: s.id, label: s.label, sequence: i + 1 })),
  };
}

// Suitability filter mirror
type StopSuitability = { infantsAllowed: boolean; minimumAge: number };
function filterStops<T extends { id: string; label: string }>(
  stops: T[],
  suitability: Record<string, StopSuitability>,
  comp: Composition,
): T[] {
  const hasInfant = comp.minorAges.some((a) => a <= 4);
  const minAge = Math.min(...comp.minorAges, 999);
  const out: T[] = [];
  const seen = new Set<string>();
  for (const s of stops) {
    const rec = suitability[s.id];
    if (!rec) continue;
    if (hasInfant && !rec.infantsAllowed) continue;
    if (minAge < rec.minimumAge) continue;
    if (seen.has(s.id)) continue;
    seen.add(s.id);
    out.push(s);
  }
  return out;
}

describe("Slice D — Studio identity guard", () => {
  it("commercialProductKey remains studio-v3-private-full-day", () => {
    expect(isStudioCommercialProductKey(STUDIO_COMMERCIAL_PRODUCT_KEY)).toBe(true);
    expect(() => assertStudioCommercialIdentity(STUDIO_COMMERCIAL_PRODUCT_KEY)).not.toThrow();
  });
  it("throws if a Signature bokunProductId leaks into the commercial key slot", () => {
    expect(() => assertStudioCommercialIdentity("signature-arrabida-boat")).toThrow(
      /studio-identity-guard/,
    );
    expect(() => assertStudioCommercialIdentity("bkn_prod_12345")).toThrow(/studio-identity-guard/);
  });
});

describe("Slice D — suitability filter never produces duplicates or Signature IDs", () => {
  const stops = [
    { id: "cabo-espichel", label: "Cabo Espichel", bokunProductId: null },
    { id: "arrabida-boat", label: "Arrabida Boat", bokunProductId: "signature-arrabida-boat" },
    { id: "sesimbra-viewpoint", label: "Sesimbra Viewpoint", bokunProductId: null },
    { id: "cabo-espichel", label: "Cabo Espichel", bokunProductId: null }, // duplicate injected
  ];
  const suitability: Record<string, StopSuitability> = {
    "cabo-espichel": { infantsAllowed: true, minimumAge: 0 },
    "arrabida-boat": { infantsAllowed: false, minimumAge: 4 }, // incompatible with infant
    "sesimbra-viewpoint": { infantsAllowed: true, minimumAge: 0 },
  };
  const comp: Composition = { adults: 2, minorAges: [15, 8, 0] };

  it("incompatible stop is dropped, no duplicates, no Signature IDs in the Studio payload", () => {
    const filtered = filterStops(stops, suitability, comp);
    const ids = filtered.map((s) => s.id);
    expect(new Set(ids).size).toBe(ids.length); // no dupes
    expect(ids).not.toContain("arrabida-boat");
    // Nothing in the resulting Studio quote payload carries a Signature bokunProductId.
    const anySignature = filtered.some((s) => s.bokunProductId != null);
    expect(anySignature).toBe(false);
  });
});

describe("Slice D — canonical route snapshot equality across surfaces", () => {
  const comp: Composition = { adults: 2, minorAges: [15, 8, 0] };
  const filteredStops = [
    { id: "cabo-espichel", label: "Cabo Espichel" },
    { id: "sesimbra-viewpoint", label: "Sesimbra Viewpoint" },
    { id: "portinho", label: "Portinho da Arrábida" },
  ];

  // Simulate the quote-time snapshot being persisted once.
  const persisted = normalizeSnapshot(STUDIO_COMMERCIAL_PRODUCT_KEY, comp, filteredStops);

  // Simulate each downstream surface reading the persisted snapshot verbatim.
  const storyboard = persisted;
  const finalItinerary = persisted;
  const checkoutSummary = persisted;
  const storedBookingQuote = persisted;
  const confirmationPayload = persisted;

  it("Storyboard / Final / Checkout / stored / confirmation snapshots are identical", () => {
    expect(finalItinerary).toEqual(storyboard);
    expect(checkoutSummary).toEqual(storyboard);
    expect(storedBookingQuote).toEqual(storyboard);
    expect(confirmationPayload).toEqual(storyboard);
    // Structural sanity
    expect(storyboard.commercialProductKey).toBe(STUDIO_COMMERCIAL_PRODUCT_KEY);
    expect(storyboard.orderedStops.map((s) => s.sequence)).toEqual([1, 2, 3]);
  });

  it("confirmation MUST read persisted snapshot — never re-run resolveStudioV3Route()", () => {
    const resolveStudioV3Route = vi.fn(() => {
      throw new Error("resolveStudioV3Route called after quote stored");
    });
    // Downstream renderers read the snapshot; they never invoke the resolver.
    const renderPdfLikeConfirmation = (snap: CanonicalRouteSnapshot) => ({
      title: `Studio Day — ${snap.travellerComposition.adults + snap.travellerComposition.minorAges.length} guests`,
      stops: snap.orderedStops.map((s) => s.label),
    });
    const rendered = renderPdfLikeConfirmation(confirmationPayload);
    expect(rendered.stops).toEqual(["Cabo Espichel", "Sesimbra Viewpoint", "Portinho da Arrábida"]);
    expect(resolveStudioV3Route).not.toHaveBeenCalled();
  });

  it("minorAges normalization is order-independent (snapshot equality is stable)", () => {
    const reordered = normalizeSnapshot(
      STUDIO_COMMERCIAL_PRODUCT_KEY,
      { adults: 2, minorAges: [0, 15, 8] },
      filteredStops,
    );
    expect(reordered).toEqual(persisted);
  });
});
