/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypographyAuditRouteImport } from './routes/typography-audit'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as PreviewCheckRouteImport } from './routes/preview-check'
import { Route as MultiDayRouteImport } from './routes/multi-day'
import { Route as LocalStoriesRouteImport } from './routes/local-stories'
import { Route as HeroVerifyRouteImport } from './routes/hero-verify'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as DayToursRouteImport } from './routes/day-tours'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as BrandQaRouteImport } from './routes/brand-qa'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursTourIdRouteImport } from './routes/tours.$tourId'
import { Route as QaMobileRouteImport } from './routes/qa.mobile'
import { Route as QaHeroRouteImport } from './routes/qa.hero'
import { Route as E2ePostmessageProbeRouteImport } from './routes/e2e.postmessage-probe'
import { Route as ApiVerifyHeroRouteImport } from './routes/api/verify-hero'
import { Route as ApiImgRouteImport } from './routes/api/img'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AdminTourLinkAuditRouteImport } from './routes/admin.tour-link-audit'
import { Route as AdminImportToursRouteImport } from './routes/admin.import-tours'
import { Route as AdminBuilderImagesQaRouteImport } from './routes/admin.builder-images-qa'
import { Route as AdminBuilderImagesRouteImport } from './routes/admin.builder-images'
import { Route as AdminAiAuditRouteImport } from './routes/admin.ai-audit'
import { Route as ToursTourIdTailorRouteImport } from './routes/tours.$tourId.tailor'

const TypographyAuditRoute = TypographyAuditRouteImport.update({
  id: '/typography-audit',
  path: '/typography-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewCheckRoute = PreviewCheckRouteImport.update({
  id: '/preview-check',
  path: '/preview-check',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiDayRoute = MultiDayRouteImport.update({
  id: '/multi-day',
  path: '/multi-day',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalStoriesRoute = LocalStoriesRouteImport.update({
  id: '/local-stories',
  path: '/local-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroVerifyRoute = HeroVerifyRouteImport.update({
  id: '/hero-verify',
  path: '/hero-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const DayToursRoute = DayToursRouteImport.update({
  id: '/day-tours',
  path: '/day-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandQaRoute = BrandQaRouteImport.update({
  id: '/brand-qa',
  path: '/brand-qa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursTourIdRoute = ToursTourIdRouteImport.update({
  id: '/tours/$tourId',
  path: '/tours/$tourId',
  getParentRoute: () => rootRouteImport,
} as any)
const QaMobileRoute = QaMobileRouteImport.update({
  id: '/qa/mobile',
  path: '/qa/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const QaHeroRoute = QaHeroRouteImport.update({
  id: '/qa/hero',
  path: '/qa/hero',
  getParentRoute: () => rootRouteImport,
} as any)
const E2ePostmessageProbeRoute = E2ePostmessageProbeRouteImport.update({
  id: '/e2e/postmessage-probe',
  path: '/e2e/postmessage-probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyHeroRoute = ApiVerifyHeroRouteImport.update({
  id: '/api/verify-hero',
  path: '/api/verify-hero',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImgRoute = ApiImgRouteImport.update({
  id: '/api/img',
  path: '/api/img',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTourLinkAuditRoute = AdminTourLinkAuditRouteImport.update({
  id: '/admin/tour-link-audit',
  path: '/admin/tour-link-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportToursRoute = AdminImportToursRouteImport.update({
  id: '/admin/import-tours',
  path: '/admin/import-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuilderImagesQaRoute = AdminBuilderImagesQaRouteImport.update({
  id: '/admin/builder-images-qa',
  path: '/admin/builder-images-qa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuilderImagesRoute = AdminBuilderImagesRouteImport.update({
  id: '/admin/builder-images',
  path: '/admin/builder-images',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiAuditRoute = AdminAiAuditRouteImport.update({
  id: '/admin/ai-audit',
  path: '/admin/ai-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursTourIdTailorRoute = ToursTourIdTailorRouteImport.update({
  id: '/tailor',
  path: '/tailor',
  getParentRoute: () => ToursTourIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/brand-qa': typeof BrandQaRoute
  '/builder': typeof BuilderRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/day-tours': typeof DayToursRoute
  '/experiences': typeof ExperiencesRoute
  '/hero-verify': typeof HeroVerifyRoute
  '/local-stories': typeof LocalStoriesRoute
  '/multi-day': typeof MultiDayRoute
  '/preview-check': typeof PreviewCheckRoute
  '/proposals': typeof ProposalsRoute
  '/typography-audit': typeof TypographyAuditRoute
  '/admin/ai-audit': typeof AdminAiAuditRoute
  '/admin/builder-images': typeof AdminBuilderImagesRoute
  '/admin/builder-images-qa': typeof AdminBuilderImagesQaRoute
  '/admin/import-tours': typeof AdminImportToursRoute
  '/admin/tour-link-audit': typeof AdminTourLinkAuditRoute
  '/api/health': typeof ApiHealthRoute
  '/api/img': typeof ApiImgRoute
  '/api/verify-hero': typeof ApiVerifyHeroRoute
  '/e2e/postmessage-probe': typeof E2ePostmessageProbeRoute
  '/qa/hero': typeof QaHeroRoute
  '/qa/mobile': typeof QaMobileRoute
  '/tours/$tourId': typeof ToursTourIdRouteWithChildren
  '/tours/$tourId/tailor': typeof ToursTourIdTailorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/brand-qa': typeof BrandQaRoute
  '/builder': typeof BuilderRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/day-tours': typeof DayToursRoute
  '/experiences': typeof ExperiencesRoute
  '/hero-verify': typeof HeroVerifyRoute
  '/local-stories': typeof LocalStoriesRoute
  '/multi-day': typeof MultiDayRoute
  '/preview-check': typeof PreviewCheckRoute
  '/proposals': typeof ProposalsRoute
  '/typography-audit': typeof TypographyAuditRoute
  '/admin/ai-audit': typeof AdminAiAuditRoute
  '/admin/builder-images': typeof AdminBuilderImagesRoute
  '/admin/builder-images-qa': typeof AdminBuilderImagesQaRoute
  '/admin/import-tours': typeof AdminImportToursRoute
  '/admin/tour-link-audit': typeof AdminTourLinkAuditRoute
  '/api/health': typeof ApiHealthRoute
  '/api/img': typeof ApiImgRoute
  '/api/verify-hero': typeof ApiVerifyHeroRoute
  '/e2e/postmessage-probe': typeof E2ePostmessageProbeRoute
  '/qa/hero': typeof QaHeroRoute
  '/qa/mobile': typeof QaMobileRoute
  '/tours/$tourId': typeof ToursTourIdRouteWithChildren
  '/tours/$tourId/tailor': typeof ToursTourIdTailorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/brand-qa': typeof BrandQaRoute
  '/builder': typeof BuilderRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/day-tours': typeof DayToursRoute
  '/experiences': typeof ExperiencesRoute
  '/hero-verify': typeof HeroVerifyRoute
  '/local-stories': typeof LocalStoriesRoute
  '/multi-day': typeof MultiDayRoute
  '/preview-check': typeof PreviewCheckRoute
  '/proposals': typeof ProposalsRoute
  '/typography-audit': typeof TypographyAuditRoute
  '/admin/ai-audit': typeof AdminAiAuditRoute
  '/admin/builder-images': typeof AdminBuilderImagesRoute
  '/admin/builder-images-qa': typeof AdminBuilderImagesQaRoute
  '/admin/import-tours': typeof AdminImportToursRoute
  '/admin/tour-link-audit': typeof AdminTourLinkAuditRoute
  '/api/health': typeof ApiHealthRoute
  '/api/img': typeof ApiImgRoute
  '/api/verify-hero': typeof ApiVerifyHeroRoute
  '/e2e/postmessage-probe': typeof E2ePostmessageProbeRoute
  '/qa/hero': typeof QaHeroRoute
  '/qa/mobile': typeof QaMobileRoute
  '/tours/$tourId': typeof ToursTourIdRouteWithChildren
  '/tours/$tourId/tailor': typeof ToursTourIdTailorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/brand-qa'
    | '/builder'
    | '/contact'
    | '/corporate'
    | '/day-tours'
    | '/experiences'
    | '/hero-verify'
    | '/local-stories'
    | '/multi-day'
    | '/preview-check'
    | '/proposals'
    | '/typography-audit'
    | '/admin/ai-audit'
    | '/admin/builder-images'
    | '/admin/builder-images-qa'
    | '/admin/import-tours'
    | '/admin/tour-link-audit'
    | '/api/health'
    | '/api/img'
    | '/api/verify-hero'
    | '/e2e/postmessage-probe'
    | '/qa/hero'
    | '/qa/mobile'
    | '/tours/$tourId'
    | '/tours/$tourId/tailor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/brand-qa'
    | '/builder'
    | '/contact'
    | '/corporate'
    | '/day-tours'
    | '/experiences'
    | '/hero-verify'
    | '/local-stories'
    | '/multi-day'
    | '/preview-check'
    | '/proposals'
    | '/typography-audit'
    | '/admin/ai-audit'
    | '/admin/builder-images'
    | '/admin/builder-images-qa'
    | '/admin/import-tours'
    | '/admin/tour-link-audit'
    | '/api/health'
    | '/api/img'
    | '/api/verify-hero'
    | '/e2e/postmessage-probe'
    | '/qa/hero'
    | '/qa/mobile'
    | '/tours/$tourId'
    | '/tours/$tourId/tailor'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/brand-qa'
    | '/builder'
    | '/contact'
    | '/corporate'
    | '/day-tours'
    | '/experiences'
    | '/hero-verify'
    | '/local-stories'
    | '/multi-day'
    | '/preview-check'
    | '/proposals'
    | '/typography-audit'
    | '/admin/ai-audit'
    | '/admin/builder-images'
    | '/admin/builder-images-qa'
    | '/admin/import-tours'
    | '/admin/tour-link-audit'
    | '/api/health'
    | '/api/img'
    | '/api/verify-hero'
    | '/e2e/postmessage-probe'
    | '/qa/hero'
    | '/qa/mobile'
    | '/tours/$tourId'
    | '/tours/$tourId/tailor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BrandQaRoute: typeof BrandQaRoute
  BuilderRoute: typeof BuilderRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  DayToursRoute: typeof DayToursRoute
  ExperiencesRoute: typeof ExperiencesRoute
  HeroVerifyRoute: typeof HeroVerifyRoute
  LocalStoriesRoute: typeof LocalStoriesRoute
  MultiDayRoute: typeof MultiDayRoute
  PreviewCheckRoute: typeof PreviewCheckRoute
  ProposalsRoute: typeof ProposalsRoute
  TypographyAuditRoute: typeof TypographyAuditRoute
  AdminAiAuditRoute: typeof AdminAiAuditRoute
  AdminBuilderImagesRoute: typeof AdminBuilderImagesRoute
  AdminBuilderImagesQaRoute: typeof AdminBuilderImagesQaRoute
  AdminImportToursRoute: typeof AdminImportToursRoute
  AdminTourLinkAuditRoute: typeof AdminTourLinkAuditRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiImgRoute: typeof ApiImgRoute
  ApiVerifyHeroRoute: typeof ApiVerifyHeroRoute
  E2ePostmessageProbeRoute: typeof E2ePostmessageProbeRoute
  QaHeroRoute: typeof QaHeroRoute
  QaMobileRoute: typeof QaMobileRoute
  ToursTourIdRoute: typeof ToursTourIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/typography-audit': {
      id: '/typography-audit'
      path: '/typography-audit'
      fullPath: '/typography-audit'
      preLoaderRoute: typeof TypographyAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-check': {
      id: '/preview-check'
      path: '/preview-check'
      fullPath: '/preview-check'
      preLoaderRoute: typeof PreviewCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-day': {
      id: '/multi-day'
      path: '/multi-day'
      fullPath: '/multi-day'
      preLoaderRoute: typeof MultiDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-stories': {
      id: '/local-stories'
      path: '/local-stories'
      fullPath: '/local-stories'
      preLoaderRoute: typeof LocalStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-verify': {
      id: '/hero-verify'
      path: '/hero-verify'
      fullPath: '/hero-verify'
      preLoaderRoute: typeof HeroVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day-tours': {
      id: '/day-tours'
      path: '/day-tours'
      fullPath: '/day-tours'
      preLoaderRoute: typeof DayToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-qa': {
      id: '/brand-qa'
      path: '/brand-qa'
      fullPath: '/brand-qa'
      preLoaderRoute: typeof BrandQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$tourId': {
      id: '/tours/$tourId'
      path: '/tours/$tourId'
      fullPath: '/tours/$tourId'
      preLoaderRoute: typeof ToursTourIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/mobile': {
      id: '/qa/mobile'
      path: '/qa/mobile'
      fullPath: '/qa/mobile'
      preLoaderRoute: typeof QaMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/hero': {
      id: '/qa/hero'
      path: '/qa/hero'
      fullPath: '/qa/hero'
      preLoaderRoute: typeof QaHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/postmessage-probe': {
      id: '/e2e/postmessage-probe'
      path: '/e2e/postmessage-probe'
      fullPath: '/e2e/postmessage-probe'
      preLoaderRoute: typeof E2ePostmessageProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-hero': {
      id: '/api/verify-hero'
      path: '/api/verify-hero'
      fullPath: '/api/verify-hero'
      preLoaderRoute: typeof ApiVerifyHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/img': {
      id: '/api/img'
      path: '/api/img'
      fullPath: '/api/img'
      preLoaderRoute: typeof ApiImgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tour-link-audit': {
      id: '/admin/tour-link-audit'
      path: '/admin/tour-link-audit'
      fullPath: '/admin/tour-link-audit'
      preLoaderRoute: typeof AdminTourLinkAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import-tours': {
      id: '/admin/import-tours'
      path: '/admin/import-tours'
      fullPath: '/admin/import-tours'
      preLoaderRoute: typeof AdminImportToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/builder-images-qa': {
      id: '/admin/builder-images-qa'
      path: '/admin/builder-images-qa'
      fullPath: '/admin/builder-images-qa'
      preLoaderRoute: typeof AdminBuilderImagesQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/builder-images': {
      id: '/admin/builder-images'
      path: '/admin/builder-images'
      fullPath: '/admin/builder-images'
      preLoaderRoute: typeof AdminBuilderImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-audit': {
      id: '/admin/ai-audit'
      path: '/admin/ai-audit'
      fullPath: '/admin/ai-audit'
      preLoaderRoute: typeof AdminAiAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$tourId/tailor': {
      id: '/tours/$tourId/tailor'
      path: '/tailor'
      fullPath: '/tours/$tourId/tailor'
      preLoaderRoute: typeof ToursTourIdTailorRouteImport
      parentRoute: typeof ToursTourIdRoute
    }
  }
}

interface ToursTourIdRouteChildren {
  ToursTourIdTailorRoute: typeof ToursTourIdTailorRoute
}

const ToursTourIdRouteChildren: ToursTourIdRouteChildren = {
  ToursTourIdTailorRoute: ToursTourIdTailorRoute,
}

const ToursTourIdRouteWithChildren = ToursTourIdRoute._addFileChildren(
  ToursTourIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BrandQaRoute: BrandQaRoute,
  BuilderRoute: BuilderRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  DayToursRoute: DayToursRoute,
  ExperiencesRoute: ExperiencesRoute,
  HeroVerifyRoute: HeroVerifyRoute,
  LocalStoriesRoute: LocalStoriesRoute,
  MultiDayRoute: MultiDayRoute,
  PreviewCheckRoute: PreviewCheckRoute,
  ProposalsRoute: ProposalsRoute,
  TypographyAuditRoute: TypographyAuditRoute,
  AdminAiAuditRoute: AdminAiAuditRoute,
  AdminBuilderImagesRoute: AdminBuilderImagesRoute,
  AdminBuilderImagesQaRoute: AdminBuilderImagesQaRoute,
  AdminImportToursRoute: AdminImportToursRoute,
  AdminTourLinkAuditRoute: AdminTourLinkAuditRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiImgRoute: ApiImgRoute,
  ApiVerifyHeroRoute: ApiVerifyHeroRoute,
  E2ePostmessageProbeRoute: E2ePostmessageProbeRoute,
  QaHeroRoute: QaHeroRoute,
  QaMobileRoute: QaMobileRoute,
  ToursTourIdRoute: ToursTourIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
