/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TypographyAuditRouteImport } from './routes/typography-audit'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StudioV3RouteImport } from './routes/studio-v3'
import { Route as StudioV2RouteImport } from './routes/studio-v2'
import { Route as StudioDriftRouteImport } from './routes/studio-drift'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PreviewCheckRouteImport } from './routes/preview-check'
import { Route as MultiDayRouteImport } from './routes/multi-day'
import { Route as LocalStoriesRouteImport } from './routes/local-stories'
import { Route as HeroVerifyRouteImport } from './routes/hero-verify'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as DayTripsFromLisbonRouteImport } from './routes/day-trips-from-lisbon'
import { Route as DayToursRouteImport } from './routes/day-tours'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as BrandQaRouteImport } from './routes/brand-qa'
import { Route as BookingConfirmedRouteImport } from './routes/booking-confirmed'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursTourIdRouteImport } from './routes/tours.$tourId'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as QaMobileRouteImport } from './routes/qa.mobile'
import { Route as QaHeroRouteImport } from './routes/qa.hero'
import { Route as LocalStoriesSlugRouteImport } from './routes/local-stories.$slug'
import { Route as ITokenRouteImport } from './routes/i.$token'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as E2ePostmessageProbeRouteImport } from './routes/e2e.postmessage-probe'
import { Route as CheckoutTokenRouteImport } from './routes/checkout.$token'
import { Route as ApiVerifyHeroRouteImport } from './routes/api/verify-hero'
import { Route as ApiImgRouteImport } from './routes/api/img'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AdminViatorValidationRouteImport } from './routes/admin.viator-validation'
import { Route as AdminTourLinkAuditRouteImport } from './routes/admin.tour-link-audit'
import { Route as AdminStudioV3FunnelRouteImport } from './routes/admin.studio-v3-funnel'
import { Route as AdminStudioV3AuditRouteImport } from './routes/admin.studio-v3-audit'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminImportToursRouteImport } from './routes/admin.import-tours'
import { Route as AdminErrorLogsRouteImport } from './routes/admin.error-logs'
import { Route as AdminDriftBibleRouteImport } from './routes/admin.drift-bible'
import { Route as AdminDriftBehaviorRouteImport } from './routes/admin.drift-behavior'
import { Route as AdminBuilderImagesQaRouteImport } from './routes/admin.builder-images-qa'
import { Route as AdminBuilderImagesRouteImport } from './routes/admin.builder-images'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminBokunMappingRouteImport } from './routes/admin.bokun-mapping'
import { Route as AdminAiAuditRouteImport } from './routes/admin.ai-audit'
import { Route as ToursTourIdTailorRouteImport } from './routes/tours.$tourId.tailor'
import { Route as StudioV2ITokenRouteImport } from './routes/studio-v2.i.$token'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TypographyAuditRoute = TypographyAuditRouteImport.update({
  id: '/typography-audit',
  path: '/typography-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioV3Route = StudioV3RouteImport.update({
  id: '/studio-v3',
  path: '/studio-v3',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioV2Route = StudioV2RouteImport.update({
  id: '/studio-v2',
  path: '/studio-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioDriftRoute = StudioDriftRouteImport.update({
  id: '/studio-drift',
  path: '/studio-drift',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewCheckRoute = PreviewCheckRouteImport.update({
  id: '/preview-check',
  path: '/preview-check',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiDayRoute = MultiDayRouteImport.update({
  id: '/multi-day',
  path: '/multi-day',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalStoriesRoute = LocalStoriesRouteImport.update({
  id: '/local-stories',
  path: '/local-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroVerifyRoute = HeroVerifyRouteImport.update({
  id: '/hero-verify',
  path: '/hero-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const DayTripsFromLisbonRoute = DayTripsFromLisbonRouteImport.update({
  id: '/day-trips-from-lisbon',
  path: '/day-trips-from-lisbon',
  getParentRoute: () => rootRouteImport,
} as any)
const DayToursRoute = DayToursRouteImport.update({
  id: '/day-tours',
  path: '/day-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandQaRoute = BrandQaRouteImport.update({
  id: '/brand-qa',
  path: '/brand-qa',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmedRoute = BookingConfirmedRouteImport.update({
  id: '/booking-confirmed',
  path: '/booking-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursTourIdRoute = ToursTourIdRouteImport.update({
  id: '/tours/$tourId',
  path: '/tours/$tourId',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const QaMobileRoute = QaMobileRouteImport.update({
  id: '/qa/mobile',
  path: '/qa/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const QaHeroRoute = QaHeroRouteImport.update({
  id: '/qa/hero',
  path: '/qa/hero',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalStoriesSlugRoute = LocalStoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocalStoriesRoute,
} as any)
const ITokenRoute = ITokenRouteImport.update({
  id: '/i/$token',
  path: '/i/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const E2ePostmessageProbeRoute = E2ePostmessageProbeRouteImport.update({
  id: '/e2e/postmessage-probe',
  path: '/e2e/postmessage-probe',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutTokenRoute = CheckoutTokenRouteImport.update({
  id: '/checkout/$token',
  path: '/checkout/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyHeroRoute = ApiVerifyHeroRouteImport.update({
  id: '/api/verify-hero',
  path: '/api/verify-hero',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImgRoute = ApiImgRouteImport.update({
  id: '/api/img',
  path: '/api/img',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminViatorValidationRoute = AdminViatorValidationRouteImport.update({
  id: '/admin/viator-validation',
  path: '/admin/viator-validation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTourLinkAuditRoute = AdminTourLinkAuditRouteImport.update({
  id: '/admin/tour-link-audit',
  path: '/admin/tour-link-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudioV3FunnelRoute = AdminStudioV3FunnelRouteImport.update({
  id: '/admin/studio-v3-funnel',
  path: '/admin/studio-v3-funnel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudioV3AuditRoute = AdminStudioV3AuditRouteImport.update({
  id: '/admin/studio-v3-audit',
  path: '/admin/studio-v3-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/admin/pricing',
  path: '/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportToursRoute = AdminImportToursRouteImport.update({
  id: '/admin/import-tours',
  path: '/admin/import-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminErrorLogsRoute = AdminErrorLogsRouteImport.update({
  id: '/admin/error-logs',
  path: '/admin/error-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriftBibleRoute = AdminDriftBibleRouteImport.update({
  id: '/admin/drift-bible',
  path: '/admin/drift-bible',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriftBehaviorRoute = AdminDriftBehaviorRouteImport.update({
  id: '/admin/drift-behavior',
  path: '/admin/drift-behavior',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuilderImagesQaRoute = AdminBuilderImagesQaRouteImport.update({
  id: '/admin/builder-images-qa',
  path: '/admin/builder-images-qa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuilderImagesRoute = AdminBuilderImagesRouteImport.update({
  id: '/admin/builder-images',
  path: '/admin/builder-images',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBokunMappingRoute = AdminBokunMappingRouteImport.update({
  id: '/admin/bokun-mapping',
  path: '/admin/bokun-mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiAuditRoute = AdminAiAuditRouteImport.update({
  id: '/admin/ai-audit',
  path: '/admin/ai-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursTourIdTailorRoute = ToursTourIdTailorRouteImport.update({
  id: '/tailor',
  path: '/tailor',
  getParentRoute: () => ToursTourIdRoute,
} as any)
const StudioV2ITokenRoute = StudioV2ITokenRouteImport.update({
  id: '/i/$token',
  path: '/i/$token',
  getParentRoute: () => StudioV2Route,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/brand-qa': typeof BrandQaRoute
  '/builder': typeof BuilderRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/day-tours': typeof DayToursRoute
  '/day-trips-from-lisbon': typeof DayTripsFromLisbonRoute
  '/experiences': typeof ExperiencesRoute
  '/hero-verify': typeof HeroVerifyRoute
  '/local-stories': typeof LocalStoriesRouteWithChildren
  '/multi-day': typeof MultiDayRoute
  '/preview-check': typeof PreviewCheckRoute
  '/privacy': typeof PrivacyRoute
  '/proposals': typeof ProposalsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio-drift': typeof StudioDriftRoute
  '/studio-v2': typeof StudioV2RouteWithChildren
  '/studio-v3': typeof StudioV3Route
  '/terms': typeof TermsRoute
  '/typography-audit': typeof TypographyAuditRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/ai-audit': typeof AdminAiAuditRoute
  '/admin/bokun-mapping': typeof AdminBokunMappingRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/builder-images': typeof AdminBuilderImagesRoute
  '/admin/builder-images-qa': typeof AdminBuilderImagesQaRoute
  '/admin/drift-behavior': typeof AdminDriftBehaviorRoute
  '/admin/drift-bible': typeof AdminDriftBibleRoute
  '/admin/error-logs': typeof AdminErrorLogsRoute
  '/admin/import-tours': typeof AdminImportToursRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/studio-v3-audit': typeof AdminStudioV3AuditRoute
  '/admin/studio-v3-funnel': typeof AdminStudioV3FunnelRoute
  '/admin/tour-link-audit': typeof AdminTourLinkAuditRoute
  '/admin/viator-validation': typeof AdminViatorValidationRoute
  '/api/health': typeof ApiHealthRoute
  '/api/img': typeof ApiImgRoute
  '/api/verify-hero': typeof ApiVerifyHeroRoute
  '/checkout/$token': typeof CheckoutTokenRoute
  '/e2e/postmessage-probe': typeof E2ePostmessageProbeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/i/$token': typeof ITokenRoute
  '/local-stories/$slug': typeof LocalStoriesSlugRoute
  '/qa/hero': typeof QaHeroRoute
  '/qa/mobile': typeof QaMobileRoute
  '/s/$token': typeof STokenRoute
  '/tours/$tourId': typeof ToursTourIdRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/studio-v2/i/$token': typeof StudioV2ITokenRoute
  '/tours/$tourId/tailor': typeof ToursTourIdTailorRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/brand-qa': typeof BrandQaRoute
  '/builder': typeof BuilderRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/day-tours': typeof DayToursRoute
  '/day-trips-from-lisbon': typeof DayTripsFromLisbonRoute
  '/experiences': typeof ExperiencesRoute
  '/hero-verify': typeof HeroVerifyRoute
  '/local-stories': typeof LocalStoriesRouteWithChildren
  '/multi-day': typeof MultiDayRoute
  '/preview-check': typeof PreviewCheckRoute
  '/privacy': typeof PrivacyRoute
  '/proposals': typeof ProposalsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio-drift': typeof StudioDriftRoute
  '/studio-v2': typeof StudioV2RouteWithChildren
  '/studio-v3': typeof StudioV3Route
  '/terms': typeof TermsRoute
  '/typography-audit': typeof TypographyAuditRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/ai-audit': typeof AdminAiAuditRoute
  '/admin/bokun-mapping': typeof AdminBokunMappingRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/builder-images': typeof AdminBuilderImagesRoute
  '/admin/builder-images-qa': typeof AdminBuilderImagesQaRoute
  '/admin/drift-behavior': typeof AdminDriftBehaviorRoute
  '/admin/drift-bible': typeof AdminDriftBibleRoute
  '/admin/error-logs': typeof AdminErrorLogsRoute
  '/admin/import-tours': typeof AdminImportToursRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/studio-v3-audit': typeof AdminStudioV3AuditRoute
  '/admin/studio-v3-funnel': typeof AdminStudioV3FunnelRoute
  '/admin/tour-link-audit': typeof AdminTourLinkAuditRoute
  '/admin/viator-validation': typeof AdminViatorValidationRoute
  '/api/health': typeof ApiHealthRoute
  '/api/img': typeof ApiImgRoute
  '/api/verify-hero': typeof ApiVerifyHeroRoute
  '/checkout/$token': typeof CheckoutTokenRoute
  '/e2e/postmessage-probe': typeof E2ePostmessageProbeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/i/$token': typeof ITokenRoute
  '/local-stories/$slug': typeof LocalStoriesSlugRoute
  '/qa/hero': typeof QaHeroRoute
  '/qa/mobile': typeof QaMobileRoute
  '/s/$token': typeof STokenRoute
  '/tours/$tourId': typeof ToursTourIdRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/studio-v2/i/$token': typeof StudioV2ITokenRoute
  '/tours/$tourId/tailor': typeof ToursTourIdTailorRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/brand-qa': typeof BrandQaRoute
  '/builder': typeof BuilderRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/day-tours': typeof DayToursRoute
  '/day-trips-from-lisbon': typeof DayTripsFromLisbonRoute
  '/experiences': typeof ExperiencesRoute
  '/hero-verify': typeof HeroVerifyRoute
  '/local-stories': typeof LocalStoriesRouteWithChildren
  '/multi-day': typeof MultiDayRoute
  '/preview-check': typeof PreviewCheckRoute
  '/privacy': typeof PrivacyRoute
  '/proposals': typeof ProposalsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio-drift': typeof StudioDriftRoute
  '/studio-v2': typeof StudioV2RouteWithChildren
  '/studio-v3': typeof StudioV3Route
  '/terms': typeof TermsRoute
  '/typography-audit': typeof TypographyAuditRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/ai-audit': typeof AdminAiAuditRoute
  '/admin/bokun-mapping': typeof AdminBokunMappingRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/builder-images': typeof AdminBuilderImagesRoute
  '/admin/builder-images-qa': typeof AdminBuilderImagesQaRoute
  '/admin/drift-behavior': typeof AdminDriftBehaviorRoute
  '/admin/drift-bible': typeof AdminDriftBibleRoute
  '/admin/error-logs': typeof AdminErrorLogsRoute
  '/admin/import-tours': typeof AdminImportToursRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/studio-v3-audit': typeof AdminStudioV3AuditRoute
  '/admin/studio-v3-funnel': typeof AdminStudioV3FunnelRoute
  '/admin/tour-link-audit': typeof AdminTourLinkAuditRoute
  '/admin/viator-validation': typeof AdminViatorValidationRoute
  '/api/health': typeof ApiHealthRoute
  '/api/img': typeof ApiImgRoute
  '/api/verify-hero': typeof ApiVerifyHeroRoute
  '/checkout/$token': typeof CheckoutTokenRoute
  '/e2e/postmessage-probe': typeof E2ePostmessageProbeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/i/$token': typeof ITokenRoute
  '/local-stories/$slug': typeof LocalStoriesSlugRoute
  '/qa/hero': typeof QaHeroRoute
  '/qa/mobile': typeof QaMobileRoute
  '/s/$token': typeof STokenRoute
  '/tours/$tourId': typeof ToursTourIdRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/studio-v2/i/$token': typeof StudioV2ITokenRoute
  '/tours/$tourId/tailor': typeof ToursTourIdTailorRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/booking-confirmed'
    | '/brand-qa'
    | '/builder'
    | '/contact'
    | '/corporate'
    | '/day-tours'
    | '/day-trips-from-lisbon'
    | '/experiences'
    | '/hero-verify'
    | '/local-stories'
    | '/multi-day'
    | '/preview-check'
    | '/privacy'
    | '/proposals'
    | '/sitemap.xml'
    | '/studio-drift'
    | '/studio-v2'
    | '/studio-v3'
    | '/terms'
    | '/typography-audit'
    | '/unsubscribe'
    | '/admin/ai-audit'
    | '/admin/bokun-mapping'
    | '/admin/bookings'
    | '/admin/builder-images'
    | '/admin/builder-images-qa'
    | '/admin/drift-behavior'
    | '/admin/drift-bible'
    | '/admin/error-logs'
    | '/admin/import-tours'
    | '/admin/pricing'
    | '/admin/studio-v3-audit'
    | '/admin/studio-v3-funnel'
    | '/admin/tour-link-audit'
    | '/admin/viator-validation'
    | '/api/health'
    | '/api/img'
    | '/api/verify-hero'
    | '/checkout/$token'
    | '/e2e/postmessage-probe'
    | '/email/unsubscribe'
    | '/i/$token'
    | '/local-stories/$slug'
    | '/qa/hero'
    | '/qa/mobile'
    | '/s/$token'
    | '/tours/$tourId'
    | '/lovable/email/suppression'
    | '/studio-v2/i/$token'
    | '/tours/$tourId/tailor'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/booking-confirmed'
    | '/brand-qa'
    | '/builder'
    | '/contact'
    | '/corporate'
    | '/day-tours'
    | '/day-trips-from-lisbon'
    | '/experiences'
    | '/hero-verify'
    | '/local-stories'
    | '/multi-day'
    | '/preview-check'
    | '/privacy'
    | '/proposals'
    | '/sitemap.xml'
    | '/studio-drift'
    | '/studio-v2'
    | '/studio-v3'
    | '/terms'
    | '/typography-audit'
    | '/unsubscribe'
    | '/admin/ai-audit'
    | '/admin/bokun-mapping'
    | '/admin/bookings'
    | '/admin/builder-images'
    | '/admin/builder-images-qa'
    | '/admin/drift-behavior'
    | '/admin/drift-bible'
    | '/admin/error-logs'
    | '/admin/import-tours'
    | '/admin/pricing'
    | '/admin/studio-v3-audit'
    | '/admin/studio-v3-funnel'
    | '/admin/tour-link-audit'
    | '/admin/viator-validation'
    | '/api/health'
    | '/api/img'
    | '/api/verify-hero'
    | '/checkout/$token'
    | '/e2e/postmessage-probe'
    | '/email/unsubscribe'
    | '/i/$token'
    | '/local-stories/$slug'
    | '/qa/hero'
    | '/qa/mobile'
    | '/s/$token'
    | '/tours/$tourId'
    | '/lovable/email/suppression'
    | '/studio-v2/i/$token'
    | '/tours/$tourId/tailor'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/booking-confirmed'
    | '/brand-qa'
    | '/builder'
    | '/contact'
    | '/corporate'
    | '/day-tours'
    | '/day-trips-from-lisbon'
    | '/experiences'
    | '/hero-verify'
    | '/local-stories'
    | '/multi-day'
    | '/preview-check'
    | '/privacy'
    | '/proposals'
    | '/sitemap.xml'
    | '/studio-drift'
    | '/studio-v2'
    | '/studio-v3'
    | '/terms'
    | '/typography-audit'
    | '/unsubscribe'
    | '/admin/ai-audit'
    | '/admin/bokun-mapping'
    | '/admin/bookings'
    | '/admin/builder-images'
    | '/admin/builder-images-qa'
    | '/admin/drift-behavior'
    | '/admin/drift-bible'
    | '/admin/error-logs'
    | '/admin/import-tours'
    | '/admin/pricing'
    | '/admin/studio-v3-audit'
    | '/admin/studio-v3-funnel'
    | '/admin/tour-link-audit'
    | '/admin/viator-validation'
    | '/api/health'
    | '/api/img'
    | '/api/verify-hero'
    | '/checkout/$token'
    | '/e2e/postmessage-probe'
    | '/email/unsubscribe'
    | '/i/$token'
    | '/local-stories/$slug'
    | '/qa/hero'
    | '/qa/mobile'
    | '/s/$token'
    | '/tours/$tourId'
    | '/lovable/email/suppression'
    | '/studio-v2/i/$token'
    | '/tours/$tourId/tailor'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookingConfirmedRoute: typeof BookingConfirmedRoute
  BrandQaRoute: typeof BrandQaRoute
  BuilderRoute: typeof BuilderRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  DayToursRoute: typeof DayToursRoute
  DayTripsFromLisbonRoute: typeof DayTripsFromLisbonRoute
  ExperiencesRoute: typeof ExperiencesRoute
  HeroVerifyRoute: typeof HeroVerifyRoute
  LocalStoriesRoute: typeof LocalStoriesRouteWithChildren
  MultiDayRoute: typeof MultiDayRoute
  PreviewCheckRoute: typeof PreviewCheckRoute
  PrivacyRoute: typeof PrivacyRoute
  ProposalsRoute: typeof ProposalsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioDriftRoute: typeof StudioDriftRoute
  StudioV2Route: typeof StudioV2RouteWithChildren
  StudioV3Route: typeof StudioV3Route
  TermsRoute: typeof TermsRoute
  TypographyAuditRoute: typeof TypographyAuditRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminAiAuditRoute: typeof AdminAiAuditRoute
  AdminBokunMappingRoute: typeof AdminBokunMappingRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminBuilderImagesRoute: typeof AdminBuilderImagesRoute
  AdminBuilderImagesQaRoute: typeof AdminBuilderImagesQaRoute
  AdminDriftBehaviorRoute: typeof AdminDriftBehaviorRoute
  AdminDriftBibleRoute: typeof AdminDriftBibleRoute
  AdminErrorLogsRoute: typeof AdminErrorLogsRoute
  AdminImportToursRoute: typeof AdminImportToursRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminStudioV3AuditRoute: typeof AdminStudioV3AuditRoute
  AdminStudioV3FunnelRoute: typeof AdminStudioV3FunnelRoute
  AdminTourLinkAuditRoute: typeof AdminTourLinkAuditRoute
  AdminViatorValidationRoute: typeof AdminViatorValidationRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiImgRoute: typeof ApiImgRoute
  ApiVerifyHeroRoute: typeof ApiVerifyHeroRoute
  CheckoutTokenRoute: typeof CheckoutTokenRoute
  E2ePostmessageProbeRoute: typeof E2ePostmessageProbeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ITokenRoute: typeof ITokenRoute
  QaHeroRoute: typeof QaHeroRoute
  QaMobileRoute: typeof QaMobileRoute
  STokenRoute: typeof STokenRoute
  ToursTourIdRoute: typeof ToursTourIdRouteWithChildren
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typography-audit': {
      id: '/typography-audit'
      path: '/typography-audit'
      fullPath: '/typography-audit'
      preLoaderRoute: typeof TypographyAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-v3': {
      id: '/studio-v3'
      path: '/studio-v3'
      fullPath: '/studio-v3'
      preLoaderRoute: typeof StudioV3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-v2': {
      id: '/studio-v2'
      path: '/studio-v2'
      fullPath: '/studio-v2'
      preLoaderRoute: typeof StudioV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-drift': {
      id: '/studio-drift'
      path: '/studio-drift'
      fullPath: '/studio-drift'
      preLoaderRoute: typeof StudioDriftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-check': {
      id: '/preview-check'
      path: '/preview-check'
      fullPath: '/preview-check'
      preLoaderRoute: typeof PreviewCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-day': {
      id: '/multi-day'
      path: '/multi-day'
      fullPath: '/multi-day'
      preLoaderRoute: typeof MultiDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-stories': {
      id: '/local-stories'
      path: '/local-stories'
      fullPath: '/local-stories'
      preLoaderRoute: typeof LocalStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-verify': {
      id: '/hero-verify'
      path: '/hero-verify'
      fullPath: '/hero-verify'
      preLoaderRoute: typeof HeroVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day-trips-from-lisbon': {
      id: '/day-trips-from-lisbon'
      path: '/day-trips-from-lisbon'
      fullPath: '/day-trips-from-lisbon'
      preLoaderRoute: typeof DayTripsFromLisbonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day-tours': {
      id: '/day-tours'
      path: '/day-tours'
      fullPath: '/day-tours'
      preLoaderRoute: typeof DayToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-qa': {
      id: '/brand-qa'
      path: '/brand-qa'
      fullPath: '/brand-qa'
      preLoaderRoute: typeof BrandQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmed': {
      id: '/booking-confirmed'
      path: '/booking-confirmed'
      fullPath: '/booking-confirmed'
      preLoaderRoute: typeof BookingConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$tourId': {
      id: '/tours/$tourId'
      path: '/tours/$tourId'
      fullPath: '/tours/$tourId'
      preLoaderRoute: typeof ToursTourIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/mobile': {
      id: '/qa/mobile'
      path: '/qa/mobile'
      fullPath: '/qa/mobile'
      preLoaderRoute: typeof QaMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/hero': {
      id: '/qa/hero'
      path: '/qa/hero'
      fullPath: '/qa/hero'
      preLoaderRoute: typeof QaHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-stories/$slug': {
      id: '/local-stories/$slug'
      path: '/$slug'
      fullPath: '/local-stories/$slug'
      preLoaderRoute: typeof LocalStoriesSlugRouteImport
      parentRoute: typeof LocalStoriesRoute
    }
    '/i/$token': {
      id: '/i/$token'
      path: '/i/$token'
      fullPath: '/i/$token'
      preLoaderRoute: typeof ITokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/postmessage-probe': {
      id: '/e2e/postmessage-probe'
      path: '/e2e/postmessage-probe'
      fullPath: '/e2e/postmessage-probe'
      preLoaderRoute: typeof E2ePostmessageProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$token': {
      id: '/checkout/$token'
      path: '/checkout/$token'
      fullPath: '/checkout/$token'
      preLoaderRoute: typeof CheckoutTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-hero': {
      id: '/api/verify-hero'
      path: '/api/verify-hero'
      fullPath: '/api/verify-hero'
      preLoaderRoute: typeof ApiVerifyHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/img': {
      id: '/api/img'
      path: '/api/img'
      fullPath: '/api/img'
      preLoaderRoute: typeof ApiImgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/viator-validation': {
      id: '/admin/viator-validation'
      path: '/admin/viator-validation'
      fullPath: '/admin/viator-validation'
      preLoaderRoute: typeof AdminViatorValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tour-link-audit': {
      id: '/admin/tour-link-audit'
      path: '/admin/tour-link-audit'
      fullPath: '/admin/tour-link-audit'
      preLoaderRoute: typeof AdminTourLinkAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/studio-v3-funnel': {
      id: '/admin/studio-v3-funnel'
      path: '/admin/studio-v3-funnel'
      fullPath: '/admin/studio-v3-funnel'
      preLoaderRoute: typeof AdminStudioV3FunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/studio-v3-audit': {
      id: '/admin/studio-v3-audit'
      path: '/admin/studio-v3-audit'
      fullPath: '/admin/studio-v3-audit'
      preLoaderRoute: typeof AdminStudioV3AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import-tours': {
      id: '/admin/import-tours'
      path: '/admin/import-tours'
      fullPath: '/admin/import-tours'
      preLoaderRoute: typeof AdminImportToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/error-logs': {
      id: '/admin/error-logs'
      path: '/admin/error-logs'
      fullPath: '/admin/error-logs'
      preLoaderRoute: typeof AdminErrorLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drift-bible': {
      id: '/admin/drift-bible'
      path: '/admin/drift-bible'
      fullPath: '/admin/drift-bible'
      preLoaderRoute: typeof AdminDriftBibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drift-behavior': {
      id: '/admin/drift-behavior'
      path: '/admin/drift-behavior'
      fullPath: '/admin/drift-behavior'
      preLoaderRoute: typeof AdminDriftBehaviorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/builder-images-qa': {
      id: '/admin/builder-images-qa'
      path: '/admin/builder-images-qa'
      fullPath: '/admin/builder-images-qa'
      preLoaderRoute: typeof AdminBuilderImagesQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/builder-images': {
      id: '/admin/builder-images'
      path: '/admin/builder-images'
      fullPath: '/admin/builder-images'
      preLoaderRoute: typeof AdminBuilderImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bokun-mapping': {
      id: '/admin/bokun-mapping'
      path: '/admin/bokun-mapping'
      fullPath: '/admin/bokun-mapping'
      preLoaderRoute: typeof AdminBokunMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-audit': {
      id: '/admin/ai-audit'
      path: '/admin/ai-audit'
      fullPath: '/admin/ai-audit'
      preLoaderRoute: typeof AdminAiAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$tourId/tailor': {
      id: '/tours/$tourId/tailor'
      path: '/tailor'
      fullPath: '/tours/$tourId/tailor'
      preLoaderRoute: typeof ToursTourIdTailorRouteImport
      parentRoute: typeof ToursTourIdRoute
    }
    '/studio-v2/i/$token': {
      id: '/studio-v2/i/$token'
      path: '/i/$token'
      fullPath: '/studio-v2/i/$token'
      preLoaderRoute: typeof StudioV2ITokenRouteImport
      parentRoute: typeof StudioV2Route
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LocalStoriesRouteChildren {
  LocalStoriesSlugRoute: typeof LocalStoriesSlugRoute
}

const LocalStoriesRouteChildren: LocalStoriesRouteChildren = {
  LocalStoriesSlugRoute: LocalStoriesSlugRoute,
}

const LocalStoriesRouteWithChildren = LocalStoriesRoute._addFileChildren(
  LocalStoriesRouteChildren,
)

interface StudioV2RouteChildren {
  StudioV2ITokenRoute: typeof StudioV2ITokenRoute
}

const StudioV2RouteChildren: StudioV2RouteChildren = {
  StudioV2ITokenRoute: StudioV2ITokenRoute,
}

const StudioV2RouteWithChildren = StudioV2Route._addFileChildren(
  StudioV2RouteChildren,
)

interface ToursTourIdRouteChildren {
  ToursTourIdTailorRoute: typeof ToursTourIdTailorRoute
}

const ToursTourIdRouteChildren: ToursTourIdRouteChildren = {
  ToursTourIdTailorRoute: ToursTourIdTailorRoute,
}

const ToursTourIdRouteWithChildren = ToursTourIdRoute._addFileChildren(
  ToursTourIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookingConfirmedRoute: BookingConfirmedRoute,
  BrandQaRoute: BrandQaRoute,
  BuilderRoute: BuilderRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  DayToursRoute: DayToursRoute,
  DayTripsFromLisbonRoute: DayTripsFromLisbonRoute,
  ExperiencesRoute: ExperiencesRoute,
  HeroVerifyRoute: HeroVerifyRoute,
  LocalStoriesRoute: LocalStoriesRouteWithChildren,
  MultiDayRoute: MultiDayRoute,
  PreviewCheckRoute: PreviewCheckRoute,
  PrivacyRoute: PrivacyRoute,
  ProposalsRoute: ProposalsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioDriftRoute: StudioDriftRoute,
  StudioV2Route: StudioV2RouteWithChildren,
  StudioV3Route: StudioV3Route,
  TermsRoute: TermsRoute,
  TypographyAuditRoute: TypographyAuditRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminAiAuditRoute: AdminAiAuditRoute,
  AdminBokunMappingRoute: AdminBokunMappingRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminBuilderImagesRoute: AdminBuilderImagesRoute,
  AdminBuilderImagesQaRoute: AdminBuilderImagesQaRoute,
  AdminDriftBehaviorRoute: AdminDriftBehaviorRoute,
  AdminDriftBibleRoute: AdminDriftBibleRoute,
  AdminErrorLogsRoute: AdminErrorLogsRoute,
  AdminImportToursRoute: AdminImportToursRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminStudioV3AuditRoute: AdminStudioV3AuditRoute,
  AdminStudioV3FunnelRoute: AdminStudioV3FunnelRoute,
  AdminTourLinkAuditRoute: AdminTourLinkAuditRoute,
  AdminViatorValidationRoute: AdminViatorValidationRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiImgRoute: ApiImgRoute,
  ApiVerifyHeroRoute: ApiVerifyHeroRoute,
  CheckoutTokenRoute: CheckoutTokenRoute,
  E2ePostmessageProbeRoute: E2ePostmessageProbeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ITokenRoute: ITokenRoute,
  QaHeroRoute: QaHeroRoute,
  QaMobileRoute: QaMobileRoute,
  STokenRoute: STokenRoute,
  ToursTourIdRoute: ToursTourIdRouteWithChildren,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
