/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WineToursLisbonRouteImport } from './routes/wine-tours-lisbon'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SintraDayTourFromLisbonRouteImport } from './routes/sintra-day-tour-from-lisbon'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PtRouteImport } from './routes/pt'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as ProposalInPortugalRouteImport } from './routes/proposal-in-portugal'
import { Route as PrivateWineTourLisbonRouteImport } from './routes/private-wine-tour-lisbon'
import { Route as PrivateToursPortugalRouteImport } from './routes/private-tours-portugal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PreviewCheckRouteImport } from './routes/preview-check'
import { Route as PressRouteImport } from './routes/press'
import { Route as PortugalWineToursRouteImport } from './routes/portugal-wine-tours'
import { Route as PortugalTravelDesignerRouteImport } from './routes/portugal-travel-designer'
import { Route as PortugalToursRouteImport } from './routes/portugal-tours'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as MultiDayRouteImport } from './routes/multi-day'
import { Route as MomentsRouteImport } from './routes/moments'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LuxuryToursPortugalRouteImport } from './routes/luxury-tours-portugal'
import { Route as LocalStoriesRouteImport } from './routes/local-stories'
import { Route as HeroVerifyRouteImport } from './routes/hero-verify'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as EvoraPrivateTourFromLisbonRouteImport } from './routes/evora-private-tour-from-lisbon'
import { Route as EvoraAlentejoWineTourRouteImport } from './routes/evora-alentejo-wine-tour'
import { Route as DayTripsFromLisbonRouteImport } from './routes/day-trips-from-lisbon'
import { Route as DayToursRouteImport } from './routes/day-tours'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrandQaRouteImport } from './routes/brand-qa'
import { Route as BookingConfirmedRouteImport } from './routes/booking-confirmed'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArrabidaWineTourRouteImport } from './routes/arrabida-wine-tour'
import { Route as ArrabidaDayTripFromLisbonRouteImport } from './routes/arrabida-day-trip-from-lisbon'
import { Route as AlentejoWineTourFromLisbonRouteImport } from './routes/alentejo-wine-tour-from-lisbon'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PtIndexRouteImport } from './routes/pt.index'
import { Route as LocalStoriesIndexRouteImport } from './routes/local-stories.index'
import { Route as ToursTourIdRouteImport } from './routes/tours.$tourId'
import { Route as ReviewTokenRouteImport } from './routes/review.$token'
import { Route as QaMobileRouteImport } from './routes/qa.mobile'
import { Route as QaHeroRouteImport } from './routes/qa.hero'
import { Route as PtTermsRouteImport } from './routes/pt.terms'
import { Route as PtReviewsRouteImport } from './routes/pt.reviews'
import { Route as PtProposalsRouteImport } from './routes/pt.proposals'
import { Route as PtPrivacyRouteImport } from './routes/pt.privacy'
import { Route as PtMomentsRouteImport } from './routes/pt.moments'
import { Route as PtFaqRouteImport } from './routes/pt.faq'
import { Route as PtExperiencesRouteImport } from './routes/pt.experiences'
import { Route as PtDayToursRouteImport } from './routes/pt.day-tours'
import { Route as PtCorporateRouteImport } from './routes/pt.corporate'
import { Route as PtCookiesRouteImport } from './routes/pt.cookies'
import { Route as PtContactRouteImport } from './routes/pt.contact'
import { Route as PtAboutRouteImport } from './routes/pt.about'
import { Route as PtSplatRouteImport } from './routes/pt.$'
import { Route as LocalStoriesSlugRouteImport } from './routes/local-stories.$slug'
import { Route as Itineraries10DayPrivatePortugalTourRouteImport } from './routes/itineraries.10-day-private-portugal-tour'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as E2ePostmessageProbeRouteImport } from './routes/e2e.postmessage-probe'
import { Route as ApiImgRouteImport } from './routes/api/img'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AdminWebhookEventsRouteImport } from './routes/admin.webhook-events'
import { Route as AdminViatorValidationRouteImport } from './routes/admin.viator-validation'
import { Route as AdminTourLinkAuditRouteImport } from './routes/admin.tour-link-audit'
import { Route as AdminSeoJsonldRouteImport } from './routes/admin.seo-jsonld'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminRedirectsMonitorRouteImport } from './routes/admin.redirects-monitor'
import { Route as AdminPaymentsEnvRouteImport } from './routes/admin.payments-env'
import { Route as AdminLegacyDomainsMonitorRouteImport } from './routes/admin.legacy-domains-monitor'
import { Route as AdminLegacyDomainUnlinkRouteImport } from './routes/admin.legacy-domain-unlink'
import { Route as AdminGscRouteImport } from './routes/admin.gsc'
import { Route as AdminGbpLegacyRemovalRouteImport } from './routes/admin.gbp-legacy-removal'
import { Route as AdminErrorLogsRouteImport } from './routes/admin.error-logs'
import { Route as AdminDriftBibleRouteImport } from './routes/admin.drift-bible'
import { Route as AdminDriftBehaviorRouteImport } from './routes/admin.drift-behavior'
import { Route as AdminDomainsHealthRouteImport } from './routes/admin.domains-health'
import { Route as AdminDnsWatchRouteImport } from './routes/admin.dns-watch'
import { Route as AdminBuilderImagesRouteImport } from './routes/admin.builder-images'
import { Route as AdminAiAuditRouteImport } from './routes/admin.ai-audit'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksStripeWebhookHealthRouteImport } from './routes/api/public/hooks/stripe-webhook-health'
import { Route as ApiPublicHooksImportTripadvisorReviewsRouteImport } from './routes/api/public/hooks/import-tripadvisor-reviews'
import { Route as ApiPublicHooksDnsWatchRouteImport } from './routes/api/public/hooks/dns-watch'
import { Route as ApiPublicHooksCheckoutEmailRouteImport } from './routes/api/public/hooks/checkout-email'

const WineToursLisbonRoute = WineToursLisbonRouteImport.update({
  id: '/wine-tours-lisbon',
  path: '/wine-tours-lisbon',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SintraDayTourFromLisbonRoute = SintraDayTourFromLisbonRouteImport.update({
  id: '/sintra-day-tour-from-lisbon',
  path: '/sintra-day-tour-from-lisbon',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PtRoute = PtRouteImport.update({
  id: '/pt',
  path: '/pt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalInPortugalRoute = ProposalInPortugalRouteImport.update({
  id: '/proposal-in-portugal',
  path: '/proposal-in-portugal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateWineTourLisbonRoute = PrivateWineTourLisbonRouteImport.update({
  id: '/private-wine-tour-lisbon',
  path: '/private-wine-tour-lisbon',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateToursPortugalRoute = PrivateToursPortugalRouteImport.update({
  id: '/private-tours-portugal',
  path: '/private-tours-portugal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewCheckRoute = PreviewCheckRouteImport.update({
  id: '/preview-check',
  path: '/preview-check',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PortugalWineToursRoute = PortugalWineToursRouteImport.update({
  id: '/portugal-wine-tours',
  path: '/portugal-wine-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const PortugalTravelDesignerRoute = PortugalTravelDesignerRouteImport.update({
  id: '/portugal-travel-designer',
  path: '/portugal-travel-designer',
  getParentRoute: () => rootRouteImport,
} as any)
const PortugalToursRoute = PortugalToursRouteImport.update({
  id: '/portugal-tours',
  path: '/portugal-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiDayRoute = MultiDayRouteImport.update({
  id: '/multi-day',
  path: '/multi-day',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsRoute = MomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LuxuryToursPortugalRoute = LuxuryToursPortugalRouteImport.update({
  id: '/luxury-tours-portugal',
  path: '/luxury-tours-portugal',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalStoriesRoute = LocalStoriesRouteImport.update({
  id: '/local-stories',
  path: '/local-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroVerifyRoute = HeroVerifyRouteImport.update({
  id: '/hero-verify',
  path: '/hero-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const EvoraPrivateTourFromLisbonRoute =
  EvoraPrivateTourFromLisbonRouteImport.update({
    id: '/evora-private-tour-from-lisbon',
    path: '/evora-private-tour-from-lisbon',
    getParentRoute: () => rootRouteImport,
  } as any)
const EvoraAlentejoWineTourRoute = EvoraAlentejoWineTourRouteImport.update({
  id: '/evora-alentejo-wine-tour',
  path: '/evora-alentejo-wine-tour',
  getParentRoute: () => rootRouteImport,
} as any)
const DayTripsFromLisbonRoute = DayTripsFromLisbonRouteImport.update({
  id: '/day-trips-from-lisbon',
  path: '/day-trips-from-lisbon',
  getParentRoute: () => rootRouteImport,
} as any)
const DayToursRoute = DayToursRouteImport.update({
  id: '/day-tours',
  path: '/day-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandQaRoute = BrandQaRouteImport.update({
  id: '/brand-qa',
  path: '/brand-qa',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmedRoute = BookingConfirmedRouteImport.update({
  id: '/booking-confirmed',
  path: '/booking-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrabidaWineTourRoute = ArrabidaWineTourRouteImport.update({
  id: '/arrabida-wine-tour',
  path: '/arrabida-wine-tour',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrabidaDayTripFromLisbonRoute =
  ArrabidaDayTripFromLisbonRouteImport.update({
    id: '/arrabida-day-trip-from-lisbon',
    path: '/arrabida-day-trip-from-lisbon',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlentejoWineTourFromLisbonRoute =
  AlentejoWineTourFromLisbonRouteImport.update({
    id: '/alentejo-wine-tour-from-lisbon',
    path: '/alentejo-wine-tour-from-lisbon',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PtIndexRoute = PtIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PtRoute,
} as any)
const LocalStoriesIndexRoute = LocalStoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocalStoriesRoute,
} as any)
const ToursTourIdRoute = ToursTourIdRouteImport.update({
  id: '/tours/$tourId',
  path: '/tours/$tourId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewTokenRoute = ReviewTokenRouteImport.update({
  id: '/review/$token',
  path: '/review/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const QaMobileRoute = QaMobileRouteImport.update({
  id: '/qa/mobile',
  path: '/qa/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const QaHeroRoute = QaHeroRouteImport.update({
  id: '/qa/hero',
  path: '/qa/hero',
  getParentRoute: () => rootRouteImport,
} as any)
const PtTermsRoute = PtTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PtRoute,
} as any)
const PtReviewsRoute = PtReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => PtRoute,
} as any)
const PtProposalsRoute = PtProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => PtRoute,
} as any)
const PtPrivacyRoute = PtPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PtRoute,
} as any)
const PtMomentsRoute = PtMomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => PtRoute,
} as any)
const PtFaqRoute = PtFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PtRoute,
} as any)
const PtExperiencesRoute = PtExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => PtRoute,
} as any)
const PtDayToursRoute = PtDayToursRouteImport.update({
  id: '/day-tours',
  path: '/day-tours',
  getParentRoute: () => PtRoute,
} as any)
const PtCorporateRoute = PtCorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => PtRoute,
} as any)
const PtCookiesRoute = PtCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => PtRoute,
} as any)
const PtContactRoute = PtContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PtRoute,
} as any)
const PtAboutRoute = PtAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PtRoute,
} as any)
const PtSplatRoute = PtSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PtRoute,
} as any)
const LocalStoriesSlugRoute = LocalStoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocalStoriesRoute,
} as any)
const Itineraries10DayPrivatePortugalTourRoute =
  Itineraries10DayPrivatePortugalTourRouteImport.update({
    id: '/itineraries/10-day-private-portugal-tour',
    path: '/itineraries/10-day-private-portugal-tour',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const E2ePostmessageProbeRoute = E2ePostmessageProbeRouteImport.update({
  id: '/e2e/postmessage-probe',
  path: '/e2e/postmessage-probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImgRoute = ApiImgRouteImport.update({
  id: '/api/img',
  path: '/api/img',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebhookEventsRoute = AdminWebhookEventsRouteImport.update({
  id: '/admin/webhook-events',
  path: '/admin/webhook-events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminViatorValidationRoute = AdminViatorValidationRouteImport.update({
  id: '/admin/viator-validation',
  path: '/admin/viator-validation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTourLinkAuditRoute = AdminTourLinkAuditRouteImport.update({
  id: '/admin/tour-link-audit',
  path: '/admin/tour-link-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoJsonldRoute = AdminSeoJsonldRouteImport.update({
  id: '/admin/seo-jsonld',
  path: '/admin/seo-jsonld',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRedirectsMonitorRoute = AdminRedirectsMonitorRouteImport.update({
  id: '/admin/redirects-monitor',
  path: '/admin/redirects-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsEnvRoute = AdminPaymentsEnvRouteImport.update({
  id: '/admin/payments-env',
  path: '/admin/payments-env',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLegacyDomainsMonitorRoute =
  AdminLegacyDomainsMonitorRouteImport.update({
    id: '/admin/legacy-domains-monitor',
    path: '/admin/legacy-domains-monitor',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminLegacyDomainUnlinkRoute = AdminLegacyDomainUnlinkRouteImport.update({
  id: '/admin/legacy-domain-unlink',
  path: '/admin/legacy-domain-unlink',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGscRoute = AdminGscRouteImport.update({
  id: '/admin/gsc',
  path: '/admin/gsc',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGbpLegacyRemovalRoute = AdminGbpLegacyRemovalRouteImport.update({
  id: '/admin/gbp-legacy-removal',
  path: '/admin/gbp-legacy-removal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminErrorLogsRoute = AdminErrorLogsRouteImport.update({
  id: '/admin/error-logs',
  path: '/admin/error-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriftBibleRoute = AdminDriftBibleRouteImport.update({
  id: '/admin/drift-bible',
  path: '/admin/drift-bible',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriftBehaviorRoute = AdminDriftBehaviorRouteImport.update({
  id: '/admin/drift-behavior',
  path: '/admin/drift-behavior',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDomainsHealthRoute = AdminDomainsHealthRouteImport.update({
  id: '/admin/domains-health',
  path: '/admin/domains-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDnsWatchRoute = AdminDnsWatchRouteImport.update({
  id: '/admin/dns-watch',
  path: '/admin/dns-watch',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuilderImagesRoute = AdminBuilderImagesRouteImport.update({
  id: '/admin/builder-images',
  path: '/admin/builder-images',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiAuditRoute = AdminAiAuditRouteImport.update({
  id: '/admin/ai-audit',
  path: '/admin/ai-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksStripeWebhookHealthRoute =
  ApiPublicHooksStripeWebhookHealthRouteImport.update({
    id: '/api/public/hooks/stripe-webhook-health',
    path: '/api/public/hooks/stripe-webhook-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksImportTripadvisorReviewsRoute =
  ApiPublicHooksImportTripadvisorReviewsRouteImport.update({
    id: '/api/public/hooks/import-tripadvisor-reviews',
    path: '/api/public/hooks/import-tripadvisor-reviews',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDnsWatchRoute = ApiPublicHooksDnsWatchRouteImport.update({
  id: '/api/public/hooks/dns-watch',
  path: '/api/public/hooks/dns-watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCheckoutEmailRoute =
  ApiPublicHooksCheckoutEmailRouteImport.update({
    id: '/api/public/hooks/checkout-email',
    path: '/api/public/hooks/checkout-email',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alentejo-wine-tour-from-lisbon': typeof AlentejoWineTourFromLisbonRoute
  '/arrabida-day-trip-from-lisbon': typeof ArrabidaDayTripFromLisbonRoute
  '/arrabida-wine-tour': typeof ArrabidaWineTourRoute
  '/auth': typeof AuthRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/brand-qa': typeof BrandQaRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/corporate': typeof CorporateRoute
  '/day-tours': typeof DayToursRoute
  '/day-trips-from-lisbon': typeof DayTripsFromLisbonRoute
  '/evora-alentejo-wine-tour': typeof EvoraAlentejoWineTourRoute
  '/evora-private-tour-from-lisbon': typeof EvoraPrivateTourFromLisbonRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/hero-verify': typeof HeroVerifyRoute
  '/local-stories': typeof LocalStoriesRouteWithChildren
  '/luxury-tours-portugal': typeof LuxuryToursPortugalRoute
  '/mcp': typeof McpRoute
  '/moments': typeof MomentsRoute
  '/multi-day': typeof MultiDayRoute
  '/plan': typeof PlanRoute
  '/portugal-tours': typeof PortugalToursRoute
  '/portugal-travel-designer': typeof PortugalTravelDesignerRoute
  '/portugal-wine-tours': typeof PortugalWineToursRoute
  '/press': typeof PressRoute
  '/preview-check': typeof PreviewCheckRoute
  '/privacy': typeof PrivacyRoute
  '/private-tours-portugal': typeof PrivateToursPortugalRoute
  '/private-wine-tour-lisbon': typeof PrivateWineTourLisbonRoute
  '/proposal-in-portugal': typeof ProposalInPortugalRoute
  '/proposals': typeof ProposalsRoute
  '/pt': typeof PtRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/sintra-day-tour-from-lisbon': typeof SintraDayTourFromLisbonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/wine-tours-lisbon': typeof WineToursLisbonRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ai-audit': typeof AdminAiAuditRoute
  '/admin/builder-images': typeof AdminBuilderImagesRoute
  '/admin/dns-watch': typeof AdminDnsWatchRoute
  '/admin/domains-health': typeof AdminDomainsHealthRoute
  '/admin/drift-behavior': typeof AdminDriftBehaviorRoute
  '/admin/drift-bible': typeof AdminDriftBibleRoute
  '/admin/error-logs': typeof AdminErrorLogsRoute
  '/admin/gbp-legacy-removal': typeof AdminGbpLegacyRemovalRoute
  '/admin/gsc': typeof AdminGscRoute
  '/admin/legacy-domain-unlink': typeof AdminLegacyDomainUnlinkRoute
  '/admin/legacy-domains-monitor': typeof AdminLegacyDomainsMonitorRoute
  '/admin/payments-env': typeof AdminPaymentsEnvRoute
  '/admin/redirects-monitor': typeof AdminRedirectsMonitorRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo-jsonld': typeof AdminSeoJsonldRoute
  '/admin/tour-link-audit': typeof AdminTourLinkAuditRoute
  '/admin/viator-validation': typeof AdminViatorValidationRoute
  '/admin/webhook-events': typeof AdminWebhookEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/img': typeof ApiImgRoute
  '/e2e/postmessage-probe': typeof E2ePostmessageProbeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/itineraries/10-day-private-portugal-tour': typeof Itineraries10DayPrivatePortugalTourRoute
  '/local-stories/$slug': typeof LocalStoriesSlugRoute
  '/pt/$': typeof PtSplatRoute
  '/pt/about': typeof PtAboutRoute
  '/pt/contact': typeof PtContactRoute
  '/pt/cookies': typeof PtCookiesRoute
  '/pt/corporate': typeof PtCorporateRoute
  '/pt/day-tours': typeof PtDayToursRoute
  '/pt/experiences': typeof PtExperiencesRoute
  '/pt/faq': typeof PtFaqRoute
  '/pt/moments': typeof PtMomentsRoute
  '/pt/privacy': typeof PtPrivacyRoute
  '/pt/proposals': typeof PtProposalsRoute
  '/pt/reviews': typeof PtReviewsRoute
  '/pt/terms': typeof PtTermsRoute
  '/qa/hero': typeof QaHeroRoute
  '/qa/mobile': typeof QaMobileRoute
  '/review/$token': typeof ReviewTokenRoute
  '/tours/$tourId': typeof ToursTourIdRoute
  '/local-stories/': typeof LocalStoriesIndexRoute
  '/pt/': typeof PtIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/checkout-email': typeof ApiPublicHooksCheckoutEmailRoute
  '/api/public/hooks/dns-watch': typeof ApiPublicHooksDnsWatchRoute
  '/api/public/hooks/import-tripadvisor-reviews': typeof ApiPublicHooksImportTripadvisorReviewsRoute
  '/api/public/hooks/stripe-webhook-health': typeof ApiPublicHooksStripeWebhookHealthRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alentejo-wine-tour-from-lisbon': typeof AlentejoWineTourFromLisbonRoute
  '/arrabida-day-trip-from-lisbon': typeof ArrabidaDayTripFromLisbonRoute
  '/arrabida-wine-tour': typeof ArrabidaWineTourRoute
  '/auth': typeof AuthRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/brand-qa': typeof BrandQaRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/corporate': typeof CorporateRoute
  '/day-tours': typeof DayToursRoute
  '/day-trips-from-lisbon': typeof DayTripsFromLisbonRoute
  '/evora-alentejo-wine-tour': typeof EvoraAlentejoWineTourRoute
  '/evora-private-tour-from-lisbon': typeof EvoraPrivateTourFromLisbonRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/hero-verify': typeof HeroVerifyRoute
  '/luxury-tours-portugal': typeof LuxuryToursPortugalRoute
  '/mcp': typeof McpRoute
  '/moments': typeof MomentsRoute
  '/multi-day': typeof MultiDayRoute
  '/plan': typeof PlanRoute
  '/portugal-tours': typeof PortugalToursRoute
  '/portugal-travel-designer': typeof PortugalTravelDesignerRoute
  '/portugal-wine-tours': typeof PortugalWineToursRoute
  '/press': typeof PressRoute
  '/preview-check': typeof PreviewCheckRoute
  '/privacy': typeof PrivacyRoute
  '/private-tours-portugal': typeof PrivateToursPortugalRoute
  '/private-wine-tour-lisbon': typeof PrivateWineTourLisbonRoute
  '/proposal-in-portugal': typeof ProposalInPortugalRoute
  '/proposals': typeof ProposalsRoute
  '/reviews': typeof ReviewsRoute
  '/sintra-day-tour-from-lisbon': typeof SintraDayTourFromLisbonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/wine-tours-lisbon': typeof WineToursLisbonRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ai-audit': typeof AdminAiAuditRoute
  '/admin/builder-images': typeof AdminBuilderImagesRoute
  '/admin/dns-watch': typeof AdminDnsWatchRoute
  '/admin/domains-health': typeof AdminDomainsHealthRoute
  '/admin/drift-behavior': typeof AdminDriftBehaviorRoute
  '/admin/drift-bible': typeof AdminDriftBibleRoute
  '/admin/error-logs': typeof AdminErrorLogsRoute
  '/admin/gbp-legacy-removal': typeof AdminGbpLegacyRemovalRoute
  '/admin/gsc': typeof AdminGscRoute
  '/admin/legacy-domain-unlink': typeof AdminLegacyDomainUnlinkRoute
  '/admin/legacy-domains-monitor': typeof AdminLegacyDomainsMonitorRoute
  '/admin/payments-env': typeof AdminPaymentsEnvRoute
  '/admin/redirects-monitor': typeof AdminRedirectsMonitorRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo-jsonld': typeof AdminSeoJsonldRoute
  '/admin/tour-link-audit': typeof AdminTourLinkAuditRoute
  '/admin/viator-validation': typeof AdminViatorValidationRoute
  '/admin/webhook-events': typeof AdminWebhookEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/img': typeof ApiImgRoute
  '/e2e/postmessage-probe': typeof E2ePostmessageProbeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/itineraries/10-day-private-portugal-tour': typeof Itineraries10DayPrivatePortugalTourRoute
  '/local-stories/$slug': typeof LocalStoriesSlugRoute
  '/pt/$': typeof PtSplatRoute
  '/pt/about': typeof PtAboutRoute
  '/pt/contact': typeof PtContactRoute
  '/pt/cookies': typeof PtCookiesRoute
  '/pt/corporate': typeof PtCorporateRoute
  '/pt/day-tours': typeof PtDayToursRoute
  '/pt/experiences': typeof PtExperiencesRoute
  '/pt/faq': typeof PtFaqRoute
  '/pt/moments': typeof PtMomentsRoute
  '/pt/privacy': typeof PtPrivacyRoute
  '/pt/proposals': typeof PtProposalsRoute
  '/pt/reviews': typeof PtReviewsRoute
  '/pt/terms': typeof PtTermsRoute
  '/qa/hero': typeof QaHeroRoute
  '/qa/mobile': typeof QaMobileRoute
  '/review/$token': typeof ReviewTokenRoute
  '/tours/$tourId': typeof ToursTourIdRoute
  '/local-stories': typeof LocalStoriesIndexRoute
  '/pt': typeof PtIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/checkout-email': typeof ApiPublicHooksCheckoutEmailRoute
  '/api/public/hooks/dns-watch': typeof ApiPublicHooksDnsWatchRoute
  '/api/public/hooks/import-tripadvisor-reviews': typeof ApiPublicHooksImportTripadvisorReviewsRoute
  '/api/public/hooks/stripe-webhook-health': typeof ApiPublicHooksStripeWebhookHealthRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alentejo-wine-tour-from-lisbon': typeof AlentejoWineTourFromLisbonRoute
  '/arrabida-day-trip-from-lisbon': typeof ArrabidaDayTripFromLisbonRoute
  '/arrabida-wine-tour': typeof ArrabidaWineTourRoute
  '/auth': typeof AuthRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/brand-qa': typeof BrandQaRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/corporate': typeof CorporateRoute
  '/day-tours': typeof DayToursRoute
  '/day-trips-from-lisbon': typeof DayTripsFromLisbonRoute
  '/evora-alentejo-wine-tour': typeof EvoraAlentejoWineTourRoute
  '/evora-private-tour-from-lisbon': typeof EvoraPrivateTourFromLisbonRoute
  '/experiences': typeof ExperiencesRoute
  '/faq': typeof FaqRoute
  '/hero-verify': typeof HeroVerifyRoute
  '/local-stories': typeof LocalStoriesRouteWithChildren
  '/luxury-tours-portugal': typeof LuxuryToursPortugalRoute
  '/mcp': typeof McpRoute
  '/moments': typeof MomentsRoute
  '/multi-day': typeof MultiDayRoute
  '/plan': typeof PlanRoute
  '/portugal-tours': typeof PortugalToursRoute
  '/portugal-travel-designer': typeof PortugalTravelDesignerRoute
  '/portugal-wine-tours': typeof PortugalWineToursRoute
  '/press': typeof PressRoute
  '/preview-check': typeof PreviewCheckRoute
  '/privacy': typeof PrivacyRoute
  '/private-tours-portugal': typeof PrivateToursPortugalRoute
  '/private-wine-tour-lisbon': typeof PrivateWineTourLisbonRoute
  '/proposal-in-portugal': typeof ProposalInPortugalRoute
  '/proposals': typeof ProposalsRoute
  '/pt': typeof PtRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/sintra-day-tour-from-lisbon': typeof SintraDayTourFromLisbonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/wine-tours-lisbon': typeof WineToursLisbonRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ai-audit': typeof AdminAiAuditRoute
  '/admin/builder-images': typeof AdminBuilderImagesRoute
  '/admin/dns-watch': typeof AdminDnsWatchRoute
  '/admin/domains-health': typeof AdminDomainsHealthRoute
  '/admin/drift-behavior': typeof AdminDriftBehaviorRoute
  '/admin/drift-bible': typeof AdminDriftBibleRoute
  '/admin/error-logs': typeof AdminErrorLogsRoute
  '/admin/gbp-legacy-removal': typeof AdminGbpLegacyRemovalRoute
  '/admin/gsc': typeof AdminGscRoute
  '/admin/legacy-domain-unlink': typeof AdminLegacyDomainUnlinkRoute
  '/admin/legacy-domains-monitor': typeof AdminLegacyDomainsMonitorRoute
  '/admin/payments-env': typeof AdminPaymentsEnvRoute
  '/admin/redirects-monitor': typeof AdminRedirectsMonitorRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo-jsonld': typeof AdminSeoJsonldRoute
  '/admin/tour-link-audit': typeof AdminTourLinkAuditRoute
  '/admin/viator-validation': typeof AdminViatorValidationRoute
  '/admin/webhook-events': typeof AdminWebhookEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/img': typeof ApiImgRoute
  '/e2e/postmessage-probe': typeof E2ePostmessageProbeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/itineraries/10-day-private-portugal-tour': typeof Itineraries10DayPrivatePortugalTourRoute
  '/local-stories/$slug': typeof LocalStoriesSlugRoute
  '/pt/$': typeof PtSplatRoute
  '/pt/about': typeof PtAboutRoute
  '/pt/contact': typeof PtContactRoute
  '/pt/cookies': typeof PtCookiesRoute
  '/pt/corporate': typeof PtCorporateRoute
  '/pt/day-tours': typeof PtDayToursRoute
  '/pt/experiences': typeof PtExperiencesRoute
  '/pt/faq': typeof PtFaqRoute
  '/pt/moments': typeof PtMomentsRoute
  '/pt/privacy': typeof PtPrivacyRoute
  '/pt/proposals': typeof PtProposalsRoute
  '/pt/reviews': typeof PtReviewsRoute
  '/pt/terms': typeof PtTermsRoute
  '/qa/hero': typeof QaHeroRoute
  '/qa/mobile': typeof QaMobileRoute
  '/review/$token': typeof ReviewTokenRoute
  '/tours/$tourId': typeof ToursTourIdRoute
  '/local-stories/': typeof LocalStoriesIndexRoute
  '/pt/': typeof PtIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/checkout-email': typeof ApiPublicHooksCheckoutEmailRoute
  '/api/public/hooks/dns-watch': typeof ApiPublicHooksDnsWatchRoute
  '/api/public/hooks/import-tripadvisor-reviews': typeof ApiPublicHooksImportTripadvisorReviewsRoute
  '/api/public/hooks/stripe-webhook-health': typeof ApiPublicHooksStripeWebhookHealthRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alentejo-wine-tour-from-lisbon'
    | '/arrabida-day-trip-from-lisbon'
    | '/arrabida-wine-tour'
    | '/auth'
    | '/booking-confirmed'
    | '/brand-qa'
    | '/contact'
    | '/cookies'
    | '/corporate'
    | '/day-tours'
    | '/day-trips-from-lisbon'
    | '/evora-alentejo-wine-tour'
    | '/evora-private-tour-from-lisbon'
    | '/experiences'
    | '/faq'
    | '/hero-verify'
    | '/local-stories'
    | '/luxury-tours-portugal'
    | '/mcp'
    | '/moments'
    | '/multi-day'
    | '/plan'
    | '/portugal-tours'
    | '/portugal-travel-designer'
    | '/portugal-wine-tours'
    | '/press'
    | '/preview-check'
    | '/privacy'
    | '/private-tours-portugal'
    | '/private-wine-tour-lisbon'
    | '/proposal-in-portugal'
    | '/proposals'
    | '/pt'
    | '/reviews'
    | '/sintra-day-tour-from-lisbon'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/wine-tours-lisbon'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ai-audit'
    | '/admin/builder-images'
    | '/admin/dns-watch'
    | '/admin/domains-health'
    | '/admin/drift-behavior'
    | '/admin/drift-bible'
    | '/admin/error-logs'
    | '/admin/gbp-legacy-removal'
    | '/admin/gsc'
    | '/admin/legacy-domain-unlink'
    | '/admin/legacy-domains-monitor'
    | '/admin/payments-env'
    | '/admin/redirects-monitor'
    | '/admin/reviews'
    | '/admin/seo-jsonld'
    | '/admin/tour-link-audit'
    | '/admin/viator-validation'
    | '/admin/webhook-events'
    | '/api/health'
    | '/api/img'
    | '/e2e/postmessage-probe'
    | '/email/unsubscribe'
    | '/itineraries/10-day-private-portugal-tour'
    | '/local-stories/$slug'
    | '/pt/$'
    | '/pt/about'
    | '/pt/contact'
    | '/pt/cookies'
    | '/pt/corporate'
    | '/pt/day-tours'
    | '/pt/experiences'
    | '/pt/faq'
    | '/pt/moments'
    | '/pt/privacy'
    | '/pt/proposals'
    | '/pt/reviews'
    | '/pt/terms'
    | '/qa/hero'
    | '/qa/mobile'
    | '/review/$token'
    | '/tours/$tourId'
    | '/local-stories/'
    | '/pt/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/api/public/hooks/checkout-email'
    | '/api/public/hooks/dns-watch'
    | '/api/public/hooks/import-tripadvisor-reviews'
    | '/api/public/hooks/stripe-webhook-health'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alentejo-wine-tour-from-lisbon'
    | '/arrabida-day-trip-from-lisbon'
    | '/arrabida-wine-tour'
    | '/auth'
    | '/booking-confirmed'
    | '/brand-qa'
    | '/contact'
    | '/cookies'
    | '/corporate'
    | '/day-tours'
    | '/day-trips-from-lisbon'
    | '/evora-alentejo-wine-tour'
    | '/evora-private-tour-from-lisbon'
    | '/experiences'
    | '/faq'
    | '/hero-verify'
    | '/luxury-tours-portugal'
    | '/mcp'
    | '/moments'
    | '/multi-day'
    | '/plan'
    | '/portugal-tours'
    | '/portugal-travel-designer'
    | '/portugal-wine-tours'
    | '/press'
    | '/preview-check'
    | '/privacy'
    | '/private-tours-portugal'
    | '/private-wine-tour-lisbon'
    | '/proposal-in-portugal'
    | '/proposals'
    | '/reviews'
    | '/sintra-day-tour-from-lisbon'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/wine-tours-lisbon'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ai-audit'
    | '/admin/builder-images'
    | '/admin/dns-watch'
    | '/admin/domains-health'
    | '/admin/drift-behavior'
    | '/admin/drift-bible'
    | '/admin/error-logs'
    | '/admin/gbp-legacy-removal'
    | '/admin/gsc'
    | '/admin/legacy-domain-unlink'
    | '/admin/legacy-domains-monitor'
    | '/admin/payments-env'
    | '/admin/redirects-monitor'
    | '/admin/reviews'
    | '/admin/seo-jsonld'
    | '/admin/tour-link-audit'
    | '/admin/viator-validation'
    | '/admin/webhook-events'
    | '/api/health'
    | '/api/img'
    | '/e2e/postmessage-probe'
    | '/email/unsubscribe'
    | '/itineraries/10-day-private-portugal-tour'
    | '/local-stories/$slug'
    | '/pt/$'
    | '/pt/about'
    | '/pt/contact'
    | '/pt/cookies'
    | '/pt/corporate'
    | '/pt/day-tours'
    | '/pt/experiences'
    | '/pt/faq'
    | '/pt/moments'
    | '/pt/privacy'
    | '/pt/proposals'
    | '/pt/reviews'
    | '/pt/terms'
    | '/qa/hero'
    | '/qa/mobile'
    | '/review/$token'
    | '/tours/$tourId'
    | '/local-stories'
    | '/pt'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/api/public/hooks/checkout-email'
    | '/api/public/hooks/dns-watch'
    | '/api/public/hooks/import-tripadvisor-reviews'
    | '/api/public/hooks/stripe-webhook-health'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/alentejo-wine-tour-from-lisbon'
    | '/arrabida-day-trip-from-lisbon'
    | '/arrabida-wine-tour'
    | '/auth'
    | '/booking-confirmed'
    | '/brand-qa'
    | '/contact'
    | '/cookies'
    | '/corporate'
    | '/day-tours'
    | '/day-trips-from-lisbon'
    | '/evora-alentejo-wine-tour'
    | '/evora-private-tour-from-lisbon'
    | '/experiences'
    | '/faq'
    | '/hero-verify'
    | '/local-stories'
    | '/luxury-tours-portugal'
    | '/mcp'
    | '/moments'
    | '/multi-day'
    | '/plan'
    | '/portugal-tours'
    | '/portugal-travel-designer'
    | '/portugal-wine-tours'
    | '/press'
    | '/preview-check'
    | '/privacy'
    | '/private-tours-portugal'
    | '/private-wine-tour-lisbon'
    | '/proposal-in-portugal'
    | '/proposals'
    | '/pt'
    | '/reviews'
    | '/sintra-day-tour-from-lisbon'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/wine-tours-lisbon'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ai-audit'
    | '/admin/builder-images'
    | '/admin/dns-watch'
    | '/admin/domains-health'
    | '/admin/drift-behavior'
    | '/admin/drift-bible'
    | '/admin/error-logs'
    | '/admin/gbp-legacy-removal'
    | '/admin/gsc'
    | '/admin/legacy-domain-unlink'
    | '/admin/legacy-domains-monitor'
    | '/admin/payments-env'
    | '/admin/redirects-monitor'
    | '/admin/reviews'
    | '/admin/seo-jsonld'
    | '/admin/tour-link-audit'
    | '/admin/viator-validation'
    | '/admin/webhook-events'
    | '/api/health'
    | '/api/img'
    | '/e2e/postmessage-probe'
    | '/email/unsubscribe'
    | '/itineraries/10-day-private-portugal-tour'
    | '/local-stories/$slug'
    | '/pt/$'
    | '/pt/about'
    | '/pt/contact'
    | '/pt/cookies'
    | '/pt/corporate'
    | '/pt/day-tours'
    | '/pt/experiences'
    | '/pt/faq'
    | '/pt/moments'
    | '/pt/privacy'
    | '/pt/proposals'
    | '/pt/reviews'
    | '/pt/terms'
    | '/qa/hero'
    | '/qa/mobile'
    | '/review/$token'
    | '/tours/$tourId'
    | '/local-stories/'
    | '/pt/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/api/public/hooks/checkout-email'
    | '/api/public/hooks/dns-watch'
    | '/api/public/hooks/import-tripadvisor-reviews'
    | '/api/public/hooks/stripe-webhook-health'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlentejoWineTourFromLisbonRoute: typeof AlentejoWineTourFromLisbonRoute
  ArrabidaDayTripFromLisbonRoute: typeof ArrabidaDayTripFromLisbonRoute
  ArrabidaWineTourRoute: typeof ArrabidaWineTourRoute
  AuthRoute: typeof AuthRoute
  BookingConfirmedRoute: typeof BookingConfirmedRoute
  BrandQaRoute: typeof BrandQaRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CorporateRoute: typeof CorporateRoute
  DayToursRoute: typeof DayToursRoute
  DayTripsFromLisbonRoute: typeof DayTripsFromLisbonRoute
  EvoraAlentejoWineTourRoute: typeof EvoraAlentejoWineTourRoute
  EvoraPrivateTourFromLisbonRoute: typeof EvoraPrivateTourFromLisbonRoute
  ExperiencesRoute: typeof ExperiencesRoute
  FaqRoute: typeof FaqRoute
  HeroVerifyRoute: typeof HeroVerifyRoute
  LocalStoriesRoute: typeof LocalStoriesRouteWithChildren
  LuxuryToursPortugalRoute: typeof LuxuryToursPortugalRoute
  McpRoute: typeof McpRoute
  MomentsRoute: typeof MomentsRoute
  MultiDayRoute: typeof MultiDayRoute
  PlanRoute: typeof PlanRoute
  PortugalToursRoute: typeof PortugalToursRoute
  PortugalTravelDesignerRoute: typeof PortugalTravelDesignerRoute
  PortugalWineToursRoute: typeof PortugalWineToursRoute
  PressRoute: typeof PressRoute
  PreviewCheckRoute: typeof PreviewCheckRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivateToursPortugalRoute: typeof PrivateToursPortugalRoute
  PrivateWineTourLisbonRoute: typeof PrivateWineTourLisbonRoute
  ProposalInPortugalRoute: typeof ProposalInPortugalRoute
  ProposalsRoute: typeof ProposalsRoute
  PtRoute: typeof PtRouteWithChildren
  ReviewsRoute: typeof ReviewsRoute
  SintraDayTourFromLisbonRoute: typeof SintraDayTourFromLisbonRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  WineToursLisbonRoute: typeof WineToursLisbonRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminAiAuditRoute: typeof AdminAiAuditRoute
  AdminBuilderImagesRoute: typeof AdminBuilderImagesRoute
  AdminDnsWatchRoute: typeof AdminDnsWatchRoute
  AdminDomainsHealthRoute: typeof AdminDomainsHealthRoute
  AdminDriftBehaviorRoute: typeof AdminDriftBehaviorRoute
  AdminDriftBibleRoute: typeof AdminDriftBibleRoute
  AdminErrorLogsRoute: typeof AdminErrorLogsRoute
  AdminGbpLegacyRemovalRoute: typeof AdminGbpLegacyRemovalRoute
  AdminGscRoute: typeof AdminGscRoute
  AdminLegacyDomainUnlinkRoute: typeof AdminLegacyDomainUnlinkRoute
  AdminLegacyDomainsMonitorRoute: typeof AdminLegacyDomainsMonitorRoute
  AdminPaymentsEnvRoute: typeof AdminPaymentsEnvRoute
  AdminRedirectsMonitorRoute: typeof AdminRedirectsMonitorRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSeoJsonldRoute: typeof AdminSeoJsonldRoute
  AdminTourLinkAuditRoute: typeof AdminTourLinkAuditRoute
  AdminViatorValidationRoute: typeof AdminViatorValidationRoute
  AdminWebhookEventsRoute: typeof AdminWebhookEventsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiImgRoute: typeof ApiImgRoute
  E2ePostmessageProbeRoute: typeof E2ePostmessageProbeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  Itineraries10DayPrivatePortugalTourRoute: typeof Itineraries10DayPrivatePortugalTourRoute
  QaHeroRoute: typeof QaHeroRoute
  QaMobileRoute: typeof QaMobileRoute
  ReviewTokenRoute: typeof ReviewTokenRoute
  ToursTourIdRoute: typeof ToursTourIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksCheckoutEmailRoute: typeof ApiPublicHooksCheckoutEmailRoute
  ApiPublicHooksDnsWatchRoute: typeof ApiPublicHooksDnsWatchRoute
  ApiPublicHooksImportTripadvisorReviewsRoute: typeof ApiPublicHooksImportTripadvisorReviewsRoute
  ApiPublicHooksStripeWebhookHealthRoute: typeof ApiPublicHooksStripeWebhookHealthRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wine-tours-lisbon': {
      id: '/wine-tours-lisbon'
      path: '/wine-tours-lisbon'
      fullPath: '/wine-tours-lisbon'
      preLoaderRoute: typeof WineToursLisbonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sintra-day-tour-from-lisbon': {
      id: '/sintra-day-tour-from-lisbon'
      path: '/sintra-day-tour-from-lisbon'
      fullPath: '/sintra-day-tour-from-lisbon'
      preLoaderRoute: typeof SintraDayTourFromLisbonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt': {
      id: '/pt'
      path: '/pt'
      fullPath: '/pt'
      preLoaderRoute: typeof PtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal-in-portugal': {
      id: '/proposal-in-portugal'
      path: '/proposal-in-portugal'
      fullPath: '/proposal-in-portugal'
      preLoaderRoute: typeof ProposalInPortugalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-wine-tour-lisbon': {
      id: '/private-wine-tour-lisbon'
      path: '/private-wine-tour-lisbon'
      fullPath: '/private-wine-tour-lisbon'
      preLoaderRoute: typeof PrivateWineTourLisbonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-tours-portugal': {
      id: '/private-tours-portugal'
      path: '/private-tours-portugal'
      fullPath: '/private-tours-portugal'
      preLoaderRoute: typeof PrivateToursPortugalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-check': {
      id: '/preview-check'
      path: '/preview-check'
      fullPath: '/preview-check'
      preLoaderRoute: typeof PreviewCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portugal-wine-tours': {
      id: '/portugal-wine-tours'
      path: '/portugal-wine-tours'
      fullPath: '/portugal-wine-tours'
      preLoaderRoute: typeof PortugalWineToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portugal-travel-designer': {
      id: '/portugal-travel-designer'
      path: '/portugal-travel-designer'
      fullPath: '/portugal-travel-designer'
      preLoaderRoute: typeof PortugalTravelDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portugal-tours': {
      id: '/portugal-tours'
      path: '/portugal-tours'
      fullPath: '/portugal-tours'
      preLoaderRoute: typeof PortugalToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-day': {
      id: '/multi-day'
      path: '/multi-day'
      fullPath: '/multi-day'
      preLoaderRoute: typeof MultiDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments': {
      id: '/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof MomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxury-tours-portugal': {
      id: '/luxury-tours-portugal'
      path: '/luxury-tours-portugal'
      fullPath: '/luxury-tours-portugal'
      preLoaderRoute: typeof LuxuryToursPortugalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-stories': {
      id: '/local-stories'
      path: '/local-stories'
      fullPath: '/local-stories'
      preLoaderRoute: typeof LocalStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-verify': {
      id: '/hero-verify'
      path: '/hero-verify'
      fullPath: '/hero-verify'
      preLoaderRoute: typeof HeroVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evora-private-tour-from-lisbon': {
      id: '/evora-private-tour-from-lisbon'
      path: '/evora-private-tour-from-lisbon'
      fullPath: '/evora-private-tour-from-lisbon'
      preLoaderRoute: typeof EvoraPrivateTourFromLisbonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evora-alentejo-wine-tour': {
      id: '/evora-alentejo-wine-tour'
      path: '/evora-alentejo-wine-tour'
      fullPath: '/evora-alentejo-wine-tour'
      preLoaderRoute: typeof EvoraAlentejoWineTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day-trips-from-lisbon': {
      id: '/day-trips-from-lisbon'
      path: '/day-trips-from-lisbon'
      fullPath: '/day-trips-from-lisbon'
      preLoaderRoute: typeof DayTripsFromLisbonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day-tours': {
      id: '/day-tours'
      path: '/day-tours'
      fullPath: '/day-tours'
      preLoaderRoute: typeof DayToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-qa': {
      id: '/brand-qa'
      path: '/brand-qa'
      fullPath: '/brand-qa'
      preLoaderRoute: typeof BrandQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmed': {
      id: '/booking-confirmed'
      path: '/booking-confirmed'
      fullPath: '/booking-confirmed'
      preLoaderRoute: typeof BookingConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrabida-wine-tour': {
      id: '/arrabida-wine-tour'
      path: '/arrabida-wine-tour'
      fullPath: '/arrabida-wine-tour'
      preLoaderRoute: typeof ArrabidaWineTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrabida-day-trip-from-lisbon': {
      id: '/arrabida-day-trip-from-lisbon'
      path: '/arrabida-day-trip-from-lisbon'
      fullPath: '/arrabida-day-trip-from-lisbon'
      preLoaderRoute: typeof ArrabidaDayTripFromLisbonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alentejo-wine-tour-from-lisbon': {
      id: '/alentejo-wine-tour-from-lisbon'
      path: '/alentejo-wine-tour-from-lisbon'
      fullPath: '/alentejo-wine-tour-from-lisbon'
      preLoaderRoute: typeof AlentejoWineTourFromLisbonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/': {
      id: '/pt/'
      path: '/'
      fullPath: '/pt/'
      preLoaderRoute: typeof PtIndexRouteImport
      parentRoute: typeof PtRoute
    }
    '/local-stories/': {
      id: '/local-stories/'
      path: '/'
      fullPath: '/local-stories/'
      preLoaderRoute: typeof LocalStoriesIndexRouteImport
      parentRoute: typeof LocalStoriesRoute
    }
    '/tours/$tourId': {
      id: '/tours/$tourId'
      path: '/tours/$tourId'
      fullPath: '/tours/$tourId'
      preLoaderRoute: typeof ToursTourIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$token': {
      id: '/review/$token'
      path: '/review/$token'
      fullPath: '/review/$token'
      preLoaderRoute: typeof ReviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/mobile': {
      id: '/qa/mobile'
      path: '/qa/mobile'
      fullPath: '/qa/mobile'
      preLoaderRoute: typeof QaMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/hero': {
      id: '/qa/hero'
      path: '/qa/hero'
      fullPath: '/qa/hero'
      preLoaderRoute: typeof QaHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/terms': {
      id: '/pt/terms'
      path: '/terms'
      fullPath: '/pt/terms'
      preLoaderRoute: typeof PtTermsRouteImport
      parentRoute: typeof PtRoute
    }
    '/pt/reviews': {
      id: '/pt/reviews'
      path: '/reviews'
      fullPath: '/pt/reviews'
      preLoaderRoute: typeof PtReviewsRouteImport
      parentRoute: typeof PtRoute
    }
    '/pt/proposals': {
      id: '/pt/proposals'
      path: '/proposals'
      fullPath: '/pt/proposals'
      preLoaderRoute: typeof PtProposalsRouteImport
      parentRoute: typeof PtRoute
    }
    '/pt/privacy': {
      id: '/pt/privacy'
      path: '/privacy'
      fullPath: '/pt/privacy'
      preLoaderRoute: typeof PtPrivacyRouteImport
      parentRoute: typeof PtRoute
    }
    '/pt/moments': {
      id: '/pt/moments'
      path: '/moments'
      fullPath: '/pt/moments'
      preLoaderRoute: typeof PtMomentsRouteImport
      parentRoute: typeof PtRoute
    }
    '/pt/faq': {
      id: '/pt/faq'
      path: '/faq'
      fullPath: '/pt/faq'
      preLoaderRoute: typeof PtFaqRouteImport
      parentRoute: typeof PtRoute
    }
    '/pt/experiences': {
      id: '/pt/experiences'
      path: '/experiences'
      fullPath: '/pt/experiences'
      preLoaderRoute: typeof PtExperiencesRouteImport
      parentRoute: typeof PtRoute
    }
    '/pt/day-tours': {
      id: '/pt/day-tours'
      path: '/day-tours'
      fullPath: '/pt/day-tours'
      preLoaderRoute: typeof PtDayToursRouteImport
      parentRoute: typeof PtRoute
    }
    '/pt/corporate': {
      id: '/pt/corporate'
      path: '/corporate'
      fullPath: '/pt/corporate'
      preLoaderRoute: typeof PtCorporateRouteImport
      parentRoute: typeof PtRoute
    }
    '/pt/cookies': {
      id: '/pt/cookies'
      path: '/cookies'
      fullPath: '/pt/cookies'
      preLoaderRoute: typeof PtCookiesRouteImport
      parentRoute: typeof PtRoute
    }
    '/pt/contact': {
      id: '/pt/contact'
      path: '/contact'
      fullPath: '/pt/contact'
      preLoaderRoute: typeof PtContactRouteImport
      parentRoute: typeof PtRoute
    }
    '/pt/about': {
      id: '/pt/about'
      path: '/about'
      fullPath: '/pt/about'
      preLoaderRoute: typeof PtAboutRouteImport
      parentRoute: typeof PtRoute
    }
    '/pt/$': {
      id: '/pt/$'
      path: '/$'
      fullPath: '/pt/$'
      preLoaderRoute: typeof PtSplatRouteImport
      parentRoute: typeof PtRoute
    }
    '/local-stories/$slug': {
      id: '/local-stories/$slug'
      path: '/$slug'
      fullPath: '/local-stories/$slug'
      preLoaderRoute: typeof LocalStoriesSlugRouteImport
      parentRoute: typeof LocalStoriesRoute
    }
    '/itineraries/10-day-private-portugal-tour': {
      id: '/itineraries/10-day-private-portugal-tour'
      path: '/itineraries/10-day-private-portugal-tour'
      fullPath: '/itineraries/10-day-private-portugal-tour'
      preLoaderRoute: typeof Itineraries10DayPrivatePortugalTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/postmessage-probe': {
      id: '/e2e/postmessage-probe'
      path: '/e2e/postmessage-probe'
      fullPath: '/e2e/postmessage-probe'
      preLoaderRoute: typeof E2ePostmessageProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/img': {
      id: '/api/img'
      path: '/api/img'
      fullPath: '/api/img'
      preLoaderRoute: typeof ApiImgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/webhook-events': {
      id: '/admin/webhook-events'
      path: '/admin/webhook-events'
      fullPath: '/admin/webhook-events'
      preLoaderRoute: typeof AdminWebhookEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/viator-validation': {
      id: '/admin/viator-validation'
      path: '/admin/viator-validation'
      fullPath: '/admin/viator-validation'
      preLoaderRoute: typeof AdminViatorValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tour-link-audit': {
      id: '/admin/tour-link-audit'
      path: '/admin/tour-link-audit'
      fullPath: '/admin/tour-link-audit'
      preLoaderRoute: typeof AdminTourLinkAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo-jsonld': {
      id: '/admin/seo-jsonld'
      path: '/admin/seo-jsonld'
      fullPath: '/admin/seo-jsonld'
      preLoaderRoute: typeof AdminSeoJsonldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/redirects-monitor': {
      id: '/admin/redirects-monitor'
      path: '/admin/redirects-monitor'
      fullPath: '/admin/redirects-monitor'
      preLoaderRoute: typeof AdminRedirectsMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments-env': {
      id: '/admin/payments-env'
      path: '/admin/payments-env'
      fullPath: '/admin/payments-env'
      preLoaderRoute: typeof AdminPaymentsEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/legacy-domains-monitor': {
      id: '/admin/legacy-domains-monitor'
      path: '/admin/legacy-domains-monitor'
      fullPath: '/admin/legacy-domains-monitor'
      preLoaderRoute: typeof AdminLegacyDomainsMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/legacy-domain-unlink': {
      id: '/admin/legacy-domain-unlink'
      path: '/admin/legacy-domain-unlink'
      fullPath: '/admin/legacy-domain-unlink'
      preLoaderRoute: typeof AdminLegacyDomainUnlinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gsc': {
      id: '/admin/gsc'
      path: '/admin/gsc'
      fullPath: '/admin/gsc'
      preLoaderRoute: typeof AdminGscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gbp-legacy-removal': {
      id: '/admin/gbp-legacy-removal'
      path: '/admin/gbp-legacy-removal'
      fullPath: '/admin/gbp-legacy-removal'
      preLoaderRoute: typeof AdminGbpLegacyRemovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/error-logs': {
      id: '/admin/error-logs'
      path: '/admin/error-logs'
      fullPath: '/admin/error-logs'
      preLoaderRoute: typeof AdminErrorLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drift-bible': {
      id: '/admin/drift-bible'
      path: '/admin/drift-bible'
      fullPath: '/admin/drift-bible'
      preLoaderRoute: typeof AdminDriftBibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drift-behavior': {
      id: '/admin/drift-behavior'
      path: '/admin/drift-behavior'
      fullPath: '/admin/drift-behavior'
      preLoaderRoute: typeof AdminDriftBehaviorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/domains-health': {
      id: '/admin/domains-health'
      path: '/admin/domains-health'
      fullPath: '/admin/domains-health'
      preLoaderRoute: typeof AdminDomainsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dns-watch': {
      id: '/admin/dns-watch'
      path: '/admin/dns-watch'
      fullPath: '/admin/dns-watch'
      preLoaderRoute: typeof AdminDnsWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/builder-images': {
      id: '/admin/builder-images'
      path: '/admin/builder-images'
      fullPath: '/admin/builder-images'
      preLoaderRoute: typeof AdminBuilderImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-audit': {
      id: '/admin/ai-audit'
      path: '/admin/ai-audit'
      fullPath: '/admin/ai-audit'
      preLoaderRoute: typeof AdminAiAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/stripe-webhook-health': {
      id: '/api/public/hooks/stripe-webhook-health'
      path: '/api/public/hooks/stripe-webhook-health'
      fullPath: '/api/public/hooks/stripe-webhook-health'
      preLoaderRoute: typeof ApiPublicHooksStripeWebhookHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/import-tripadvisor-reviews': {
      id: '/api/public/hooks/import-tripadvisor-reviews'
      path: '/api/public/hooks/import-tripadvisor-reviews'
      fullPath: '/api/public/hooks/import-tripadvisor-reviews'
      preLoaderRoute: typeof ApiPublicHooksImportTripadvisorReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dns-watch': {
      id: '/api/public/hooks/dns-watch'
      path: '/api/public/hooks/dns-watch'
      fullPath: '/api/public/hooks/dns-watch'
      preLoaderRoute: typeof ApiPublicHooksDnsWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/checkout-email': {
      id: '/api/public/hooks/checkout-email'
      path: '/api/public/hooks/checkout-email'
      fullPath: '/api/public/hooks/checkout-email'
      preLoaderRoute: typeof ApiPublicHooksCheckoutEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LocalStoriesRouteChildren {
  LocalStoriesSlugRoute: typeof LocalStoriesSlugRoute
  LocalStoriesIndexRoute: typeof LocalStoriesIndexRoute
}

const LocalStoriesRouteChildren: LocalStoriesRouteChildren = {
  LocalStoriesSlugRoute: LocalStoriesSlugRoute,
  LocalStoriesIndexRoute: LocalStoriesIndexRoute,
}

const LocalStoriesRouteWithChildren = LocalStoriesRoute._addFileChildren(
  LocalStoriesRouteChildren,
)

interface PtRouteChildren {
  PtSplatRoute: typeof PtSplatRoute
  PtAboutRoute: typeof PtAboutRoute
  PtContactRoute: typeof PtContactRoute
  PtCookiesRoute: typeof PtCookiesRoute
  PtCorporateRoute: typeof PtCorporateRoute
  PtDayToursRoute: typeof PtDayToursRoute
  PtExperiencesRoute: typeof PtExperiencesRoute
  PtFaqRoute: typeof PtFaqRoute
  PtMomentsRoute: typeof PtMomentsRoute
  PtPrivacyRoute: typeof PtPrivacyRoute
  PtProposalsRoute: typeof PtProposalsRoute
  PtReviewsRoute: typeof PtReviewsRoute
  PtTermsRoute: typeof PtTermsRoute
  PtIndexRoute: typeof PtIndexRoute
}

const PtRouteChildren: PtRouteChildren = {
  PtSplatRoute: PtSplatRoute,
  PtAboutRoute: PtAboutRoute,
  PtContactRoute: PtContactRoute,
  PtCookiesRoute: PtCookiesRoute,
  PtCorporateRoute: PtCorporateRoute,
  PtDayToursRoute: PtDayToursRoute,
  PtExperiencesRoute: PtExperiencesRoute,
  PtFaqRoute: PtFaqRoute,
  PtMomentsRoute: PtMomentsRoute,
  PtPrivacyRoute: PtPrivacyRoute,
  PtProposalsRoute: PtProposalsRoute,
  PtReviewsRoute: PtReviewsRoute,
  PtTermsRoute: PtTermsRoute,
  PtIndexRoute: PtIndexRoute,
}

const PtRouteWithChildren = PtRoute._addFileChildren(PtRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlentejoWineTourFromLisbonRoute: AlentejoWineTourFromLisbonRoute,
  ArrabidaDayTripFromLisbonRoute: ArrabidaDayTripFromLisbonRoute,
  ArrabidaWineTourRoute: ArrabidaWineTourRoute,
  AuthRoute: AuthRoute,
  BookingConfirmedRoute: BookingConfirmedRoute,
  BrandQaRoute: BrandQaRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CorporateRoute: CorporateRoute,
  DayToursRoute: DayToursRoute,
  DayTripsFromLisbonRoute: DayTripsFromLisbonRoute,
  EvoraAlentejoWineTourRoute: EvoraAlentejoWineTourRoute,
  EvoraPrivateTourFromLisbonRoute: EvoraPrivateTourFromLisbonRoute,
  ExperiencesRoute: ExperiencesRoute,
  FaqRoute: FaqRoute,
  HeroVerifyRoute: HeroVerifyRoute,
  LocalStoriesRoute: LocalStoriesRouteWithChildren,
  LuxuryToursPortugalRoute: LuxuryToursPortugalRoute,
  McpRoute: McpRoute,
  MomentsRoute: MomentsRoute,
  MultiDayRoute: MultiDayRoute,
  PlanRoute: PlanRoute,
  PortugalToursRoute: PortugalToursRoute,
  PortugalTravelDesignerRoute: PortugalTravelDesignerRoute,
  PortugalWineToursRoute: PortugalWineToursRoute,
  PressRoute: PressRoute,
  PreviewCheckRoute: PreviewCheckRoute,
  PrivacyRoute: PrivacyRoute,
  PrivateToursPortugalRoute: PrivateToursPortugalRoute,
  PrivateWineTourLisbonRoute: PrivateWineTourLisbonRoute,
  ProposalInPortugalRoute: ProposalInPortugalRoute,
  ProposalsRoute: ProposalsRoute,
  PtRoute: PtRouteWithChildren,
  ReviewsRoute: ReviewsRoute,
  SintraDayTourFromLisbonRoute: SintraDayTourFromLisbonRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  WineToursLisbonRoute: WineToursLisbonRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminAiAuditRoute: AdminAiAuditRoute,
  AdminBuilderImagesRoute: AdminBuilderImagesRoute,
  AdminDnsWatchRoute: AdminDnsWatchRoute,
  AdminDomainsHealthRoute: AdminDomainsHealthRoute,
  AdminDriftBehaviorRoute: AdminDriftBehaviorRoute,
  AdminDriftBibleRoute: AdminDriftBibleRoute,
  AdminErrorLogsRoute: AdminErrorLogsRoute,
  AdminGbpLegacyRemovalRoute: AdminGbpLegacyRemovalRoute,
  AdminGscRoute: AdminGscRoute,
  AdminLegacyDomainUnlinkRoute: AdminLegacyDomainUnlinkRoute,
  AdminLegacyDomainsMonitorRoute: AdminLegacyDomainsMonitorRoute,
  AdminPaymentsEnvRoute: AdminPaymentsEnvRoute,
  AdminRedirectsMonitorRoute: AdminRedirectsMonitorRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSeoJsonldRoute: AdminSeoJsonldRoute,
  AdminTourLinkAuditRoute: AdminTourLinkAuditRoute,
  AdminViatorValidationRoute: AdminViatorValidationRoute,
  AdminWebhookEventsRoute: AdminWebhookEventsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiImgRoute: ApiImgRoute,
  E2ePostmessageProbeRoute: E2ePostmessageProbeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  Itineraries10DayPrivatePortugalTourRoute:
    Itineraries10DayPrivatePortugalTourRoute,
  QaHeroRoute: QaHeroRoute,
  QaMobileRoute: QaMobileRoute,
  ReviewTokenRoute: ReviewTokenRoute,
  ToursTourIdRoute: ToursTourIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksCheckoutEmailRoute: ApiPublicHooksCheckoutEmailRoute,
  ApiPublicHooksDnsWatchRoute: ApiPublicHooksDnsWatchRoute,
  ApiPublicHooksImportTripadvisorReviewsRoute:
    ApiPublicHooksImportTripadvisorReviewsRoute,
  ApiPublicHooksStripeWebhookHealthRoute:
    ApiPublicHooksStripeWebhookHealthRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
